#!/usr/bin/env python3
"""Keep the zero-setup web parser in sync with the checked-in Wasm asset."""
import base64
from pathlib import Path
import sys
root = Path(__file__).resolve().parent.parent
encoded = base64.b64encode((root / 'lib/assets/wasm/flark_parse.wasm').read_bytes()).decode()
text = '// Generated by tool/embed_wasm.py. Do not edit.\nconst bundledParserBase64 =\n'
text += ''.join("    '" + encoded[i:i+100] + "'\n" for i in range(0, len(encoded), 100))
text = text.rstrip() + ';\n'
path = root / 'lib/src/parse/bundled_wasm.g.dart'
if '--check' in sys.argv:
    if not path.exists() or path.read_text() != text:
        sys.exit('Bundled parser is stale. Run python3 tool/embed_wasm.py.')
else:
    path.write_text(text)
