#!/usr/bin/env python3
"""Derive Rust constants, Dart constants, and SCHEMA.md from schema/render_model_v1.json."""
import json, pathlib, sys
root = pathlib.Path(__file__).resolve().parent.parent
schema = json.loads((root / 'schema' / 'render_model_v1.json').read_text())
magic = int.from_bytes(schema['magic'].encode(), 'little')

def rust():
    out = ['// Generated by tool/gen_schema.py from schema/render_model_v1.json. Do not edit.', '#![allow(dead_code)]', '']
    out.append(f'pub const VERSION: u32 = {schema["version"]};')
    out.append(f'pub const MAGIC: u32 = 0x{magic:08X}; // {schema["magic"]!r} little-endian')
    out.append(f'pub const HEADER_WORDS: usize = {len(schema["header"])};')
    out.append('pub mod header {')
    for i, f in enumerate(schema['header']): out.append(f'    pub const {f.upper()}: usize = {i};')
    out.append('}')
    for rec, fields in schema['records'].items():
        out.append(f'pub mod {rec} {{')
        out.append(f'    pub const WORDS: usize = {len(fields)};')
        for i, f in enumerate(fields): out.append(f'    pub const {f.upper()}: usize = {i};')
        out.append('}')
    for enum, values in schema['enums'].items():
        out.append(f'pub mod {enum} {{')
        for k, v in values.items(): out.append(f'    pub const {k.upper()}: u32 = {v};')
        out.append('}')
    return '\n'.join(out) + '\n'

def camel(s):
    parts = s.split('_'); return parts[0] + ''.join(p.capitalize() for p in parts[1:])

def dart():
    out = ['// Generated by native/flark_parse/tool/gen_schema.py from', '// native/flark_parse/schema/render_model_v1.json. Do not edit.', '', '// ignore_for_file: constant_identifier_names', '']
    out.append('abstract final class RenderModelSchema {')
    out.append(f'  static const int version = {schema["version"]};')
    out.append(f'  static const int magic = 0x{magic:08X};')
    out.append(f'  static const int headerWords = {len(schema["header"])};')
    for rec, fields in schema['records'].items(): out.append(f'  static const int {camel(rec)}Words = {len(fields)};')
    out.append('}')
    out.append('')
    out.append('abstract final class HeaderField {')
    for i, f in enumerate(schema['header']): out.append(f'  static const int {camel(f)} = {i};')
    out.append('}')
    for rec, fields in schema['records'].items():
        out.append('')
        out.append(f'abstract final class {rec.capitalize()}Field {{')
        for i, f in enumerate(fields): out.append(f'  static const int {camel(f)} = {i};')
        out.append('}')
    for enum, values in schema['enums'].items():
        out.append('')
        cls = ''.join(p.capitalize() for p in enum.split('_'))
        out.append(f'abstract final class {cls} {{')
        for k, v in values.items(): out.append(f'  static const int {camel(k)} = {v};')
        out.append('}')
    return '\n'.join(out) + '\n'

def md():
    out = [f'# Render model schema v{schema["version"]}', '', 'Generated from `schema/render_model_v1.json`; edit the JSON, then run `tool/gen_schema.py`.', '', schema['description'], '', f'Magic `{schema["magic"]}` (u32 `0x{magic:08X}` little-endian). Sections follow the header in this order: ' + ', '.join(schema['sections']) + '. The string table is padded to a multiple of four bytes.', '', '## Header', '', '| Word | Field |', '| --- | --- |']
    for i, f in enumerate(schema['header']): out.append(f'| {i} | `{f}` |')
    for rec, fields in schema['records'].items():
        out += ['', f'## {rec.capitalize()} record ({len(fields)} words)', '', '| Word | Field |', '| --- | --- |']
        for i, f in enumerate(fields): out.append(f'| {i} | `{f}` |')
    for enum, values in schema['enums'].items():
        out += ['', f'## {enum}', '', '| Name | Value |', '| --- | --- |']
        for k, v in values.items(): out.append(f'| `{k}` | {v} |')
    for title, attrs in (('Block attributes', schema['block_attrs']), ('Run attributes', schema['run_attrs'])):
        out += ['', f'## {title}', '', '| Kind | Field | Meaning |', '| --- | --- | --- |']
        for kind, m in attrs.items():
            for f, meaning in m.items(): out.append(f'| `{kind}` | `{f}` | {meaning} |')
    out += ['', '## Invariants', '']
    for inv in schema['invariants']: out.append(f'- {inv}')
    return '\n'.join(out) + '\n'

(root / 'src' / 'schema.rs').write_text(rust())
dart_path = root.parent.parent / 'packages' / 'flark' / 'lib' / 'src' / 'parse' / 'schema.g.dart'
dart_path.parent.mkdir(parents=True, exist_ok=True)
dart_path.write_text(dart())
(root / 'SCHEMA.md').write_text(md())
print('generated', root / 'src' / 'schema.rs', dart_path, root / 'SCHEMA.md', sep='\n  ')
