#!/usr/bin/env python3
"""Derive Rust constants, Dart constants, and SCHEMA.md from schema/render_model_v5.json."""
import json, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
schema_file = 'render_model_v5.json'
schema = json.loads((root / 'schema' / schema_file).read_text())
magic = int.from_bytes(schema['magic'].encode(), 'little')

def camel(s):
    parts = s.split('_'); return parts[0] + ''.join(p.capitalize() for p in parts[1:])

def pascal(s):
    return ''.join(p.capitalize() for p in s.replace('.', '_').split('_'))

def rust():
    out = [f'// Generated by tool/gen_schema.py from schema/{schema_file}. Do not edit.', '#![allow(dead_code)]', '']
    out.append(f'pub const VERSION: u32 = {schema["version"]};')
    out.append(f'pub const MAGIC: u32 = 0x{magic:08X}; // {schema["magic"]!r} little-endian')
    out.append(f'pub const HEADER_WORDS: usize = {len(schema["header"])};')
    out.append('pub mod header {')
    for i, f in enumerate(schema['header']): out.append(f'    pub const {f.upper()}: usize = {i};')
    out.append('}')
    for rec, fields in schema['records'].items():
        out.append(f'pub mod {rec} {{')
        out.append(f'    pub const WORDS: usize = {len(fields)};')
        for i, f in enumerate(fields): out.append(f'    pub const {f.upper()}: usize = {i};')
        packed = {k.split('.')[1]: v for k, v in schema['packed'].items() if k.split('.')[0] == rec}
        for word, parts in packed.items():
            out.append(f'    pub mod {word} {{')
            for name, shift, bits in parts:
                out.append(f'        pub const {name.upper()}_SHIFT: u32 = {shift};')
                out.append(f'        pub const {name.upper()}_MASK: u32 = 0x{(1 << bits) - 1:X};')
            out.append('    }')
        out.append('}')
    out.append('pub mod extra {')
    out.append('    pub const NONE: u32 = 0xFFFFFFFF;')
    for name, spec in schema['extras'].items():
        out.append(f'    pub mod {name} {{')
        out.append(f'        pub const WORDS: usize = {len(spec["fields"])};')
        for i, f in enumerate(spec['fields']): out.append(f'        pub const {f.upper()}: usize = {i};')
        out.append('    }')
    out.append('}')
    for enum, values in schema['enums'].items():
        out.append(f'pub mod {enum} {{')
        for k, v in values.items(): out.append(f'    pub const {k.upper()}: u32 = {v};')
        out.append('}')
    return '\n'.join(out) + '\n'

def dart():
    out = ['// Generated by native/flark_parse/tool/gen_schema.py from', f'// native/flark_parse/schema/{schema_file}. Do not edit.', '', '// ignore_for_file: constant_identifier_names', '']
    out.append('abstract final class RenderModelSchema {')
    out.append(f'  static const int version = {schema["version"]};')
    out.append(f'  static const int magic = 0x{magic:08X};')
    out.append(f'  static const int headerWords = {len(schema["header"])};')
    for rec, fields in schema['records'].items(): out.append(f'  static const int {camel(rec)}Words = {len(fields)};')
    out.append('')
    out.append('  /// A block without an extra record.')
    out.append('  static const int noExtra = 0xFFFFFFFF;')
    out.append('}')
    out.append('')
    out.append('abstract final class HeaderField {')
    for i, f in enumerate(schema['header']): out.append(f'  static const int {camel(f)} = {i};')
    out.append('}')
    for rec, fields in schema['records'].items():
        out.append('')
        out.append(f'abstract final class {pascal(rec)}Field {{')
        for i, f in enumerate(fields): out.append(f'  static const int {camel(f)} = {i};')
        out.append('}')
    for word, parts in schema['packed'].items():
        out.append('')
        out.append(f'/// Fields packed into `{word}`.')
        out.append(f'abstract final class {pascal(word)} {{')
        for name, shift, bits in parts:
            out.append(f'  static const int {camel(name)}Shift = {shift};')
            out.append(f'  static const int {camel(name)}Mask = 0x{(1 << bits) - 1:X};')
        out.append('}')
    for name, spec in schema['extras'].items():
        out.append('')
        out.append(f'/// Extra record of {spec["owner"]}.')
        out.append(f'abstract final class {pascal(name)}Extra {{')
        out.append(f'  static const int words = {len(spec["fields"])};')
        for i, f in enumerate(spec['fields']): out.append(f'  static const int {camel(f)} = {i};')
        out.append('}')
    for enum, values in schema['enums'].items():
        out.append('')
        out.append(f'abstract final class {pascal(enum)} {{')
        for k, v in values.items(): out.append(f'  static const int {camel(k)} = {v};')
        out.append('}')
    return '\n'.join(out) + '\n'

def md():
    out = [f'# Render model schema v{schema["version"]}', '', f'Generated from `schema/{schema_file}`; edit the JSON, then run `tool/gen_schema.py`.', '', schema['description'], '', f'Magic `{schema["magic"]}` (u32 `0x{magic:08X}` little-endian). Sections follow the header in this order: ' + ', '.join(schema['sections']) + '. The extras section is `extra_words` words long. The string table is padded to a multiple of four bytes.', '', '## Header', '', '| Word | Field |', '| --- | --- |']
    for i, f in enumerate(schema['header']): out.append(f'| {i} | `{f}` |')
    for rec, fields in schema['records'].items():
        out += ['', f'## {rec.replace("_", " ").capitalize()} record ({len(fields)} words)', '', '| Word | Field |', '| --- | --- |']
        for i, f in enumerate(fields): out.append(f'| {i} | `{f}` |')
    out += ['', '## Packed words', '', '| Word | Field | Bits |', '| --- | --- | --- |']
    for word, parts in schema['packed'].items():
        for name, shift, bits in parts: out.append(f'| `{word}` | `{name}` | {shift}-{shift + bits - 1} |')
    out += ['', '## Extra records', '', '| Record | Owner | Words |', '| --- | --- | --- |']
    for name, spec in schema['extras'].items():
        out.append(f'| `{name}` | {spec["owner"]} | ' + ', '.join(f'`{f}`' for f in spec['fields']) + ' |')
    for enum, values in schema['enums'].items():
        out += ['', f'## {enum}', '', '| Name | Value |', '| --- | --- |']
        for k, v in values.items(): out.append(f'| `{k}` | {v} |')
    for title, attrs in (('Block attributes', schema['block_attrs']), ('Run attributes', schema['run_attrs'])):
        out += ['', f'## {title}', '', '| Kind | Field | Meaning |', '| --- | --- | --- |']
        for kind, m in attrs.items():
            for f, meaning in m.items(): out.append(f'| `{kind}` | `{f}` | {meaning} |')
    out += ['', '## Invariants', '']
    for inv in schema['invariants']: out.append(f'- {inv}')
    return '\n'.join(out) + '\n'

(root / 'src' / 'schema.rs').write_text(rust())
dart_path = root.parent.parent / 'packages' / 'flark' / 'lib' / 'src' / 'parse' / 'schema.g.dart'
dart_path.parent.mkdir(parents=True, exist_ok=True)
dart_path.write_text(dart())
(root / 'SCHEMA.md').write_text(md())
print('generated', root / 'src' / 'schema.rs', dart_path, root / 'SCHEMA.md', sep='\n  ')
