#!/usr/bin/env python3
"""Writes packages/flark/THIRD_PARTY_NOTICES.md for the parser library.

The native library and the Wasm module link flark_parse's normal dependency
closure: comrak and the crates it builds on, plus mimalloc and its C source on
native targets. Build scripts and procedural macros run at compile time and are
not linked, so they are left out. License texts come from the crates cargo has
already fetched; run `cargo fetch` first on a fresh machine.

Usage: python3 native/flark_parse/tool/third_party_notices.py
"""
import json
import os
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
CRATE = os.path.join(ROOT, 'native', 'flark_parse')
OUT = os.path.join(ROOT, 'packages', 'flark', 'THIRD_PARTY_NOTICES.md')
# Native targets link mimalloc; the Wasm module does not. The union is listed.
TARGETS = ['aarch64-apple-darwin', 'x86_64-pc-windows-msvc', 'wasm32-unknown-unknown']
LICENSE_NAMES = ('license', 'licence', 'copying', 'notice')


def metadata(target):
    out = subprocess.run(
        ['cargo', 'metadata', '--format-version', '1', '--locked',
         '--manifest-path', os.path.join(CRATE, 'Cargo.toml'),
         '--filter-platform', target],
        check=True, capture_output=True, text=True).stdout
    return json.loads(out)


def linked(meta):
    """The root's normal dependencies, transitively, without proc macros."""
    nodes = {n['id']: n for n in meta['resolve']['nodes']}
    packages = {p['id']: p for p in meta['packages']}
    root = meta['resolve']['root']
    seen, stack = set(), [root]
    while stack:
        node = stack.pop()
        if node in seen:
            continue
        seen.add(node)
        for dep in nodes[node]['deps']:
            if not any(k['kind'] is None for k in dep['dep_kinds']):
                continue
            package = packages[dep['pkg']]
            if any('proc-macro' in t['kind'] for t in package['targets']):
                continue
            stack.append(dep['pkg'])
    seen.discard(root)
    return [packages[i] for i in seen]


def license_files(directory):
    names = sorted(
        f for f in os.listdir(directory)
        if f.lower().startswith(LICENSE_NAMES) and
        os.path.isfile(os.path.join(directory, f)))
    return [os.path.join(directory, f) for f in names]


def main():
    crates = {}
    for target in TARGETS:
        for package in linked(metadata(target)):
            crates[(package['name'], package['version'])] = package
    sections = []
    for (name, version), package in sorted(crates.items()):
        directory = os.path.dirname(package['manifest_path'])
        files = license_files(directory)
        if name == 'libmimalloc-sys':
            # The C allocator the crate compiles; v2 is the pinned feature.
            files.append(os.path.join(directory, 'c_src', 'mimalloc', 'v2', 'LICENSE'))
        if not files:
            sys.exit(f'no license file for {name} {version} in {directory}')
        repository = package.get('repository') or ''
        lines = [f'## {name} {version}', '',
                 f'License: {package["license"]}' + (f' · {repository}' if repository else ''), '']
        for path in files:
            label = os.path.relpath(path, directory)
            text = open(path, encoding='utf-8').read().strip()
            lines += [f'{label}:', '', '```text', text, '```', '']
        sections.append('\n'.join(lines))
    header = [
        '# Third-party notices',
        '',
        "The parser this package loads, as a native library or as the bundled",
        "Wasm module (`lib/assets/wasm/flark_parse.wasm`), is built from",
        "`native/flark_parse` and links the Rust crates below. mimalloc and its",
        "C source are linked on native targets only. Where a crate offers a",
        "choice of licenses, it is used under its MIT (or first-listed) terms;",
        "all offered texts are reproduced.",
        '',
        f'Generated by `native/flark_parse/tool/third_party_notices.py` from',
        '`native/flark_parse/Cargo.lock`.',
        '',
    ]
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(header) + '\n' + '\n'.join(sections))
    print(f'wrote {os.path.relpath(OUT, ROOT)}: {len(crates)} crates')


if __name__ == '__main__':
    main()
