#!/usr/bin/env python3
"""Writes packages/flark/THIRD_PARTY_NOTICES.md for the parser library.

The native library and the Wasm module link flark_parse's normal dependency
closure: comrak and the crates it builds on, plus mimalloc and its C source on
native targets, as `cargo tree` resolves it for each target. Build scripts,
procedural macros and dev-dependencies are not linked, so they are left out. License texts come from the crates cargo has
already fetched; run `cargo fetch` first on a fresh machine.

Usage: python3 native/flark_parse/tool/third_party_notices.py
"""
import json
import os
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
CRATE = os.path.join(ROOT, 'native', 'flark_parse')
OUT = os.path.join(ROOT, 'packages', 'flark', 'THIRD_PARTY_NOTICES.md')
# Native targets link mimalloc; the Wasm module does not. The union is listed.
TARGETS = ['aarch64-apple-darwin', 'x86_64-pc-windows-msvc', 'wasm32-unknown-unknown']
LICENSE_NAMES = ('license', 'licence', 'copying', 'notice')


def metadata():
    out = subprocess.run(
        ['cargo', 'metadata', '--format-version', '1', '--locked',
         '--manifest-path', os.path.join(CRATE, 'Cargo.toml')],
        check=True, capture_output=True, text=True).stdout
    return json.loads(out)


def linked(target):
    """(name, version) of every crate linked into the library for [target].

    `cargo tree` resolves features as the build does. `cargo metadata`'s
    resolve graph unifies them with dev-dependencies, so it lists crates, such
    as serde, that no build of the library links.
    """
    out = subprocess.run(
        ['cargo', 'tree', '--locked', '--edges', 'normal,no-proc-macro',
         '--target', target, '--prefix', 'none', '--format', '{p}',
         '--manifest-path', os.path.join(CRATE, 'Cargo.toml')],
        check=True, capture_output=True, text=True).stdout
    crates = set()
    for line in out.splitlines():
        fields = line.split()
        if len(fields) < 2 or fields[0] == 'flark_parse':
            continue
        crates.add((fields[0], fields[1].lstrip('v')))
    return crates


def license_files(directory):
    names = sorted(
        f for f in os.listdir(directory)
        if f.lower().startswith(LICENSE_NAMES) and
        os.path.isfile(os.path.join(directory, f)))
    return [os.path.join(directory, f) for f in names]


def main():
    packages = {(p['name'], p['version']): p for p in metadata()['packages']}
    crates = {}
    for target in TARGETS:
        for key in linked(target):
            crates[key] = packages[key]
    sections = []
    for (name, version), package in sorted(crates.items()):
        directory = os.path.dirname(package['manifest_path'])
        files = license_files(directory)
        if name == 'libmimalloc-sys':
            # The C allocator the crate compiles; v2 is the pinned feature.
            files.append(os.path.join(directory, 'c_src', 'mimalloc', 'v2', 'LICENSE'))
        if not files:
            sys.exit(f'no license file for {name} {version} in {directory}')
        repository = package.get('repository') or ''
        lines = [f'## {name} {version}', '',
                 f'License: {package["license"]}' + (f' · {repository}' if repository else ''), '']
        for path in files:
            label = os.path.relpath(path, directory)
            text = open(path, encoding='utf-8').read().strip()
            lines += [f'{label}:', '', '```text', text, '```', '']
        sections.append('\n'.join(lines))
    header = [
        '# Third-party notices',
        '',
        "The parser this package loads, as a native library or as the bundled",
        "Wasm module (`lib/assets/wasm/flark_parse.wasm`), is built from",
        "`native/flark_parse` and links the Rust crates below. mimalloc and its",
        "C source are linked on native targets only. Where a crate offers a",
        "choice of licenses, it is used under its MIT (or first-listed) terms;",
        "all offered texts are reproduced.",
        '',
        f'Generated by `native/flark_parse/tool/third_party_notices.py` from',
        '`native/flark_parse/Cargo.lock`.',
        '',
    ]
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(header) + '\n' + '\n'.join(sections))
    print(f'wrote {os.path.relpath(OUT, ROOT)}: {len(crates)} crates')


if __name__ == '__main__':
    main()
