/* Generated by re2rust 4.3.1 */
// Generated with:
// re2rust 4.3.1 --no-generation-date --storable-state --no-unsafe \
//   -o src/atx_cursor_generated.rs rules/atx_cursor.re
//
// Do not add Markdown syntax here. generate.py inserts the exact ATX pattern
// extracted from the pinned Comrak scanners.re source.

/// Immutable identity plus random/sequential byte access for one physical
/// line. Production adapters can cache a Crop cursor internally; the scanner
/// retains only absolute offsets and never owns source bytes.
pub trait AtxCursorSource {
    fn source_key(&self) -> u64;
    fn len(&self) -> usize;
    fn is_empty(&self) -> bool {
        self.len() == 0
    }
    fn byte_at(&mut self, absolute_offset: usize) -> u8;
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CursorScanResult {
    NeedMore,
    Matched(usize),
    NoMatch,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CursorScanError {
    ZeroFuel,
    WrongSource,
    SourceContainsSentinel { absolute_offset: usize },
    PollAfterComplete,
    PollAfterFailure,
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct CursorScanReceipt {
    pub result: Option<CursorScanResult>,
    pub source_bytes_inspected: usize,
    pub maximum_lookahead_slack: usize,
    pub retained_source_bytes: usize,
}

/// Exact generated DFA state over a caller-owned physical-line cursor.
///
/// `poll` may inspect at most `fuel + LOOKAHEAD_SLACK` real source bytes. The
/// constant slack is generated as `YYMAXFILL - 1`: re2c groups bounds checks
/// around the longest non-looping DFA path. This is a hard constant, not a
/// line-length-dependent buffer.
#[derive(Clone, Debug)]
pub struct CursorAtxScanner {
    source_key: u64,
    source_len: usize,
    yycursor: usize,
    yymarker: usize,
    yystate: isize,
    poll_source_limit: usize,
    poll_source_bytes: usize,
    source_error: Option<CursorScanError>,
    terminal: Option<CursorScanResult>,
    failed: bool,
}

impl CursorAtxScanner {
    #[must_use]
    pub fn new(source_key: u64, source_len: usize) -> Self {
        Self {
            source_key,
            source_len,
            yycursor: 0,
            yymarker: 0,
            yystate: -1,
            poll_source_limit: 0,
            poll_source_bytes: 0,
            source_error: None,
            terminal: None,
            failed: false,
        }
    }

    pub fn poll<S: AtxCursorSource>(
        &mut self,
        source: &mut S,
        fuel: usize,
    ) -> Result<CursorScanReceipt, CursorScanError> {
        if fuel == 0 {
            return Err(CursorScanError::ZeroFuel);
        }
        if self.failed {
            return Err(CursorScanError::PollAfterFailure);
        }
        if self.terminal.is_some() {
            return Err(CursorScanError::PollAfterComplete);
        }
        if source.source_key() != self.source_key || source.len() != self.source_len {
            self.failed = true;
            return Err(CursorScanError::WrongSource);
        }

        self.poll_source_bytes = 0;
        self.poll_source_limit = fuel.saturating_add(LOOKAHEAD_SLACK);
        self.source_error = None;
        let result = scan_cursor(self, source);
        if let Some(error) = self.source_error.take() {
            self.failed = true;
            return Err(error);
        }
        if result != CursorScanResult::NeedMore {
            self.terminal = Some(result);
        }
        Ok(CursorScanReceipt {
            result: Some(result),
            source_bytes_inspected: self.poll_source_bytes,
            maximum_lookahead_slack: LOOKAHEAD_SLACK,
            retained_source_bytes: 0,
        })
    }

    #[must_use]
    pub const fn cursor(&self) -> usize {
        if self.yycursor < self.source_len {
            self.yycursor
        } else {
            self.source_len
        }
    }

    #[must_use]
    pub const fn retained_source_bytes(&self) -> usize {
        0
    }

    fn less_than(&self, requested: usize) -> bool {
        let remaining_source = self.source_len.saturating_sub(self.yycursor);
        let real_source_needed = if requested < remaining_source {
            requested
        } else {
            remaining_source
        };
        self.poll_source_bytes.saturating_add(real_source_needed) > self.poll_source_limit
    }

    fn peek<S: AtxCursorSource>(&mut self, source: &mut S) -> u8 {
        if self.yycursor >= self.source_len {
            return 0xff;
        }
        let offset = self.yycursor;
        let byte = source.byte_at(offset);
        self.poll_source_bytes = self.poll_source_bytes.saturating_add(1);
        if byte == 0xff {
            self.source_error = Some(CursorScanError::SourceContainsSentinel {
                absolute_offset: offset,
            });
        }
        byte
    }
}

fn scan_cursor<S: AtxCursorSource>(
    scanner: &mut CursorAtxScanner,
    source: &mut S,
) -> CursorScanResult {
    let mut yych: u8;

    {
        let mut yystate: isize = scanner.yystate;
        'yyl: loop {
            match yystate {
                -1..=0 => {
                    if scanner.less_than(7) {
                        scanner.yystate = 13;
                        return CursorScanResult::NeedMore;
                    }
                    yych = scanner.peek(source);
                    scanner.yycursor += 1;
                    match yych {
                        0x23 => {
                            yystate = 3;
                            continue 'yyl;
                        }
                        _ => {
                            yystate = 1;
                            continue 'yyl;
                        }
                    }
                }
                1 => {
                    yystate = 2;
                    continue 'yyl;
                }
                2 => {
                    scanner.yystate = -1;
                    {
                        return CursorScanResult::NoMatch;
                    }
                }
                3 => {
                    scanner.yymarker = scanner.yycursor;
                    yych = scanner.peek(source);
                    match yych {
                        0x00..=0x08 | 0x0B..=0x0C | 0x0E..=0x1F | 0x21..=0x22 | 0x24..=0xFE => {
                            yystate = 2;
                            continue 'yyl;
                        }
                        0x09 | 0x20 => {
                            scanner.yycursor += 1;
                            yystate = 4;
                            continue 'yyl;
                        }
                        0x23 => {
                            scanner.yycursor += 1;
                            yystate = 7;
                            continue 'yyl;
                        }
                        _ => {
                            scanner.yycursor += 1;
                            yystate = 6;
                            continue 'yyl;
                        }
                    }
                }
                4 => {
                    if scanner.less_than(1) {
                        scanner.yystate = 14;
                        return CursorScanResult::NeedMore;
                    }
                    yych = scanner.peek(source);
                    match yych {
                        0x09 | 0x20 => {
                            scanner.yycursor += 1;
                            yystate = 4;
                            continue 'yyl;
                        }
                        _ => {
                            yystate = 5;
                            continue 'yyl;
                        }
                    }
                }
                5 => {
                    scanner.yystate = -1;
                    {
                        return CursorScanResult::Matched(scanner.yycursor.min(scanner.source_len));
                    }
                }
                6 => {
                    yystate = 5;
                    continue 'yyl;
                }
                7 => {
                    yych = scanner.peek(source);
                    match yych {
                        0x00..=0x08 | 0x0B..=0x0C | 0x0E..=0x1F | 0x21..=0x22 | 0x24..=0xFE => {
                            yystate = 8;
                            continue 'yyl;
                        }
                        0x09 | 0x20 => {
                            scanner.yycursor += 1;
                            yystate = 4;
                            continue 'yyl;
                        }
                        0x23 => {
                            scanner.yycursor += 1;
                            yystate = 9;
                            continue 'yyl;
                        }
                        _ => {
                            scanner.yycursor += 1;
                            yystate = 6;
                            continue 'yyl;
                        }
                    }
                }
                8 => {
                    scanner.yycursor = scanner.yymarker;
                    yystate = 2;
                    continue 'yyl;
                }
                9 => {
                    yych = scanner.peek(source);
                    match yych {
                        0x00..=0x08 | 0x0B..=0x0C | 0x0E..=0x1F | 0x21..=0x22 | 0x24..=0xFE => {
                            yystate = 8;
                            continue 'yyl;
                        }
                        0x09 | 0x20 => {
                            scanner.yycursor += 1;
                            yystate = 4;
                            continue 'yyl;
                        }
                        0x23 => {
                            scanner.yycursor += 1;
                            yystate = 10;
                            continue 'yyl;
                        }
                        _ => {
                            scanner.yycursor += 1;
                            yystate = 6;
                            continue 'yyl;
                        }
                    }
                }
                10 => {
                    yych = scanner.peek(source);
                    match yych {
                        0x00..=0x08 | 0x0B..=0x0C | 0x0E..=0x1F | 0x21..=0x22 | 0x24..=0xFE => {
                            yystate = 8;
                            continue 'yyl;
                        }
                        0x09 | 0x20 => {
                            scanner.yycursor += 1;
                            yystate = 4;
                            continue 'yyl;
                        }
                        0x23 => {
                            scanner.yycursor += 1;
                            yystate = 11;
                            continue 'yyl;
                        }
                        _ => {
                            scanner.yycursor += 1;
                            yystate = 6;
                            continue 'yyl;
                        }
                    }
                }
                11 => {
                    yych = scanner.peek(source);
                    match yych {
                        0x00..=0x08 | 0x0B..=0x0C | 0x0E..=0x1F | 0x21..=0x22 | 0x24..=0xFE => {
                            yystate = 8;
                            continue 'yyl;
                        }
                        0x09 | 0x20 => {
                            scanner.yycursor += 1;
                            yystate = 4;
                            continue 'yyl;
                        }
                        0x23 => {
                            scanner.yycursor += 1;
                            yystate = 12;
                            continue 'yyl;
                        }
                        _ => {
                            scanner.yycursor += 1;
                            yystate = 6;
                            continue 'yyl;
                        }
                    }
                }
                12 => {
                    yych = scanner.peek(source);
                    match yych {
                        0x00..=0x08 | 0x0B..=0x0C | 0x0E..=0x1F | 0x21..=0xFE => {
                            yystate = 8;
                            continue 'yyl;
                        }
                        0x09 | 0x20 => {
                            scanner.yycursor += 1;
                            yystate = 4;
                            continue 'yyl;
                        }
                        _ => {
                            scanner.yycursor += 1;
                            yystate = 6;
                            continue 'yyl;
                        }
                    }
                }
                13 => {
                    yystate = 0;
                    continue 'yyl;
                }
                14 => {
                    yystate = 4;
                    continue 'yyl;
                }
                _ => panic!("internal lexer error"),
            }
        }
    }
}

const YYMAXFILL: usize = 7;

/// Maximum real-source accesses the generated DFA may perform beyond one
/// caller fuel grant because re2c groups checks around its longest fixed path.
pub const CURSOR_ATX_MAX_LOOKAHEAD_SLACK: usize = YYMAXFILL - 1;

/// Maximum unique prefix bytes the pinned ATX DFA can inspect before a
/// `NoMatch`. Long separator loops are accepting paths, so the fused line
/// scanner needs no source-proportional rejection cache.
pub const CURSOR_ATX_REJECTION_PREFIX_CAP: usize = YYMAXFILL;

const LOOKAHEAD_SLACK: usize = CURSOR_ATX_MAX_LOOKAHEAD_SLACK;
