import 'package:flark_tree_sitter/flark_tree_sitter.dart';

const catalogCases = {
  CodeLanguage.dart: "void main() { print('hello'); }",
  CodeLanguage.javascript: "const value = 'hello'; console.log(value);",
  CodeLanguage.python: "def hello():\n    print('hello')",
  CodeLanguage.yaml: "name: \"hello\"\nitems: [one, two]",
  CodeLanguage.ruby: "def hello\n  print 'hello'\nend",
  CodeLanguage.typescript: "const value: string = 'hello';",
  CodeLanguage.rust: "fn main() { println!(\"hello\"); }",
  CodeLanguage.go: "package main\nfunc main() { println(\"hello\") }",
  CodeLanguage.json: "{\"hello\": [1, true]}",
  CodeLanguage.css: ".card { color: red; content: \"hello\"; }",
  CodeLanguage.bash: "if true; then\n  echo \"hello\"\nfi",
  CodeLanguage.html: "<div class=\"card\">hello</div>",
  CodeLanguage.xml: "<?xml version=\"1.0\"?><note>hello</note>",
  CodeLanguage.sql: "SELECT name FROM users WHERE name = 'hello';",
};

const detectionCases = {
  "if true; then": CodeLanguage.bash,
  "if true; then\n  echo \"hello\"\n  f": CodeLanguage.bash,
  "for x in one two; do": CodeLanguage.bash,
  "while true; do": CodeLanguage.bash,

  "if (ready) {": CodeLanguage.javascript,
  "if ready": CodeLanguage.ruby,
  "void main() { print('hello'); }": CodeLanguage.dart,
  "const value = 'hello'; console.log(value);": CodeLanguage.javascript,
  "def hello():\n    print('hello')": CodeLanguage.python,
  "name: \"hello\"\nitems: [one, two]": CodeLanguage.yaml,
  "def hello\n  print 'hello'\nend": CodeLanguage.ruby,
  "const value: string = 'hello';": CodeLanguage.typescript,
  "fn main() { println!(\"hello\"); }": CodeLanguage.rust,
  "package main\nfunc main() { println(\"hello\") }": CodeLanguage.go,
  "{\"hello\": [1, true]}": CodeLanguage.json,
  ".card { color: red; content: \"hello\"; }": CodeLanguage.css,
  "if true; then\n  echo \"hello\"\nfi": CodeLanguage.bash,
  "<div class=\"card\">hello</div>": CodeLanguage.html,
  "<?xml version=\"1.0\"?><note>hello</note>": CodeLanguage.xml,
  "SELECT name FROM users WHERE name = 'hello';": CodeLanguage.sql,
  "def hello": CodeLanguage.ruby,
  "def hello\n  ": CodeLanguage.ruby,
  "def hello():": CodeLanguage.python,
  "for (final x in [1,2,3]) {": CodeLanguage.dart,
  "settings: |": CodeLanguage.yaml,
  "echo \"hello\"": CodeLanguage.bash,
  "function hello() {": CodeLanguage.javascript,
  "": CodeLanguage.plain,
  "x": CodeLanguage.plain,
  "Hello world": CodeLanguage.plain,
  "This is a simple test.": CodeLanguage.plain,
  "Please select the item.": CodeLanguage.plain,
  "An end to the story.": CodeLanguage.plain,
  "The final result is here.": CodeLanguage.plain,
};
