import 'package:flark_tree_sitter/flark_tree_sitter.dart';

const d = CodeLanguage.dart,
    j = CodeLanguage.javascript,
    p = CodeLanguage.python,
    y = CodeLanguage.yaml,
    r = CodeLanguage.ruby;
const enter = CodeEditAction.newline,
    type = CodeEditAction.insert,
    tab = CodeEditAction.indent,
    backtab = CodeEditAction.outdent;

final class EditCase {
  const EditCase(
    this.name,
    this.language,
    this.before,
    this.action,
    this.after, {
    this.text = '',
    this.unit = '  ',
    this.newline = '\n',
  });
  final String name, before, after, text, unit, newline;
  final CodeLanguage language;
  final CodeEditAction action;
}

// Hand-authored outcomes. ¦ is a caret; «/» are base/extent (either order).
const editCases = [
  EditCase(
    'JSON Enter before first string',
    CodeLanguage.json,
    '{¦"answer": 42}',
    enter,
    '{\n  ¦"answer": 42}',
  ),
  EditCase(
    'Bash typed else aligns with then header',
    CodeLanguage.bash,
    'if ready; then\n  echo ok\n  els¦',
    type,
    'if ready; then\n  echo ok\nelse¦',
    text: 'e',
  ),
  EditCase(
    'Bash elif body Enter',
    CodeLanguage.bash,
    'if ready; then\n  echo ok\nelif other; then¦',
    enter,
    'if ready; then\n  echo ok\nelif other; then\n  ¦',
  ),
  EditCase(
    'Bash fi after branches',
    CodeLanguage.bash,
    'if ready; then\n  echo ok\nelif other; then\n  echo other\nelse\n  echo no\n  f¦',
    type,
    'if ready; then\n  echo ok\nelif other; then\n  echo other\nelse\n  echo no\nfi¦',
    text: 'i',
  ),

  EditCase(
    "typescript Enter header",
    CodeLanguage.typescript,
    "function hello(): void {¦",
    enter,
    "function hello(): void {\n  ¦",
  ),
  EditCase(
    "typescript typed closer",
    CodeLanguage.typescript,
    "function hello(): void {\n  ¦",
    type,
    "function hello(): void {\n}¦",
    text: "}",
  ),
  EditCase(
    "typescript complete literal",
    CodeLanguage.typescript,
    "const text: string = \"{\";¦",
    enter,
    "const text: string = \"{\";\n¦",
  ),
  EditCase(
    "typescript preserve body indent",
    CodeLanguage.typescript,
    "function hello(): void {\n  value¦",
    enter,
    "function hello(): void {\n  value\n  ¦",
  ),
  EditCase(
    "typescript selected lines tab",
    CodeLanguage.typescript,
    "«first\nsecond»",
    tab,
    "  «first\n  second»",
  ),
  EditCase(
    "typescript selected lines outdent",
    CodeLanguage.typescript,
    "  «first\n  second»",
    backtab,
    "«first\nsecond»",
  ),
  EditCase(
    "rust Enter header",
    CodeLanguage.rust,
    "fn main() {¦",
    enter,
    "fn main() {\n  ¦",
  ),
  EditCase(
    "rust typed closer",
    CodeLanguage.rust,
    "fn main() {\n  ¦",
    type,
    "fn main() {\n}¦",
    text: "}",
  ),
  EditCase(
    "rust complete literal",
    CodeLanguage.rust,
    "let text = r#\"{\"#;¦",
    enter,
    "let text = r#\"{\"#;\n¦",
  ),
  EditCase(
    "rust preserve body indent",
    CodeLanguage.rust,
    "fn main() {\n  value¦",
    enter,
    "fn main() {\n  value\n  ¦",
  ),
  EditCase(
    "rust selected lines tab",
    CodeLanguage.rust,
    "«first\nsecond»",
    tab,
    "  «first\n  second»",
  ),
  EditCase(
    "rust selected lines outdent",
    CodeLanguage.rust,
    "  «first\n  second»",
    backtab,
    "«first\nsecond»",
  ),
  EditCase(
    "go Enter header",
    CodeLanguage.go,
    "func main() {¦",
    enter,
    "func main() {\n  ¦",
  ),
  EditCase(
    "go typed closer",
    CodeLanguage.go,
    "func main() {\n  ¦",
    type,
    "func main() {\n}¦",
    text: "}",
  ),
  EditCase(
    "go complete literal",
    CodeLanguage.go,
    "text := `{\"`;¦",
    enter,
    "text := `{\"`;\n¦",
  ),
  EditCase(
    "go preserve body indent",
    CodeLanguage.go,
    "func main() {\n  value¦",
    enter,
    "func main() {\n  value\n  ¦",
  ),
  EditCase(
    "go selected lines tab",
    CodeLanguage.go,
    "«first\nsecond»",
    tab,
    "  «first\n  second»",
  ),
  EditCase(
    "go selected lines outdent",
    CodeLanguage.go,
    "  «first\n  second»",
    backtab,
    "«first\nsecond»",
  ),
  EditCase(
    "json Enter header",
    CodeLanguage.json,
    "{\"items\": [¦",
    enter,
    "{\"items\": [\n  ¦",
  ),
  EditCase(
    "json typed closer",
    CodeLanguage.json,
    "{\"items\": [\n  ¦",
    type,
    "{\"items\": [\n]¦",
    text: "]",
  ),
  EditCase(
    "json complete literal",
    CodeLanguage.json,
    "\"{\"¦",
    enter,
    "\"{\"\n¦",
  ),
  EditCase(
    "json preserve body indent",
    CodeLanguage.json,
    "{\"items\": [\n  value¦",
    enter,
    "{\"items\": [\n  value\n  ¦",
  ),
  EditCase(
    "json selected lines tab",
    CodeLanguage.json,
    "«first\nsecond»",
    tab,
    "  «first\n  second»",
  ),
  EditCase(
    "json selected lines outdent",
    CodeLanguage.json,
    "  «first\n  second»",
    backtab,
    "«first\nsecond»",
  ),
  EditCase(
    "css Enter header",
    CodeLanguage.css,
    ".card {¦",
    enter,
    ".card {\n  ¦",
  ),
  EditCase(
    "css typed closer",
    CodeLanguage.css,
    ".card {\n  ¦",
    type,
    ".card {\n}¦",
    text: "}",
  ),
  EditCase(
    "css complete literal",
    CodeLanguage.css,
    "content: \"{\";¦",
    enter,
    "content: \"{\";\n¦",
  ),
  EditCase(
    "css preserve body indent",
    CodeLanguage.css,
    ".card {\n  value¦",
    enter,
    ".card {\n  value\n  ¦",
  ),
  EditCase(
    "css selected lines tab",
    CodeLanguage.css,
    "«first\nsecond»",
    tab,
    "  «first\n  second»",
  ),
  EditCase(
    "css selected lines outdent",
    CodeLanguage.css,
    "  «first\n  second»",
    backtab,
    "«first\nsecond»",
  ),
  EditCase(
    "bash Enter header",
    CodeLanguage.bash,
    "if ready; then¦",
    enter,
    "if ready; then\n  ¦",
  ),
  EditCase(
    "bash typed closer",
    CodeLanguage.bash,
    "if ready; then\n  f¦",
    type,
    "if ready; then\nfi¦",
    text: "i",
  ),
  EditCase(
    "bash complete literal",
    CodeLanguage.bash,
    "echo \"{\"¦",
    enter,
    "echo \"{\"\n¦",
  ),
  EditCase(
    "bash preserve body indent",
    CodeLanguage.bash,
    "if ready; then\n  value¦",
    enter,
    "if ready; then\n  value\n  ¦",
  ),
  EditCase(
    "bash selected lines tab",
    CodeLanguage.bash,
    "«first\nsecond»",
    tab,
    "  «first\n  second»",
  ),
  EditCase(
    "bash selected lines outdent",
    CodeLanguage.bash,
    "  «first\n  second»",
    backtab,
    "«first\nsecond»",
  ),
  EditCase(
    "html Enter header",
    CodeLanguage.html,
    "<div>¦",
    enter,
    "<div>\n  ¦",
  ),
  EditCase(
    "html typed closer",
    CodeLanguage.html,
    "<div>\n  </div¦",
    type,
    "<div>\n</div>¦",
    text: ">",
  ),
  EditCase(
    "html complete literal",
    CodeLanguage.html,
    "<div title=\"{\">text</div>¦",
    enter,
    "<div title=\"{\">text</div>\n¦",
  ),
  EditCase(
    "html preserve body indent",
    CodeLanguage.html,
    "<div>\n  value¦",
    enter,
    "<div>\n  value\n  ¦",
  ),
  EditCase(
    "html selected lines tab",
    CodeLanguage.html,
    "«first\nsecond»",
    tab,
    "  «first\n  second»",
  ),
  EditCase(
    "html selected lines outdent",
    CodeLanguage.html,
    "  «first\n  second»",
    backtab,
    "«first\nsecond»",
  ),
  EditCase(
    "xml Enter header",
    CodeLanguage.xml,
    "<note>¦",
    enter,
    "<note>\n  ¦",
  ),
  EditCase(
    "xml typed closer",
    CodeLanguage.xml,
    "<note>\n  </note¦",
    type,
    "<note>\n</note>¦",
    text: ">",
  ),
  EditCase(
    "xml complete literal",
    CodeLanguage.xml,
    "<note text=\"{\"/>¦",
    enter,
    "<note text=\"{\"/>\n¦",
  ),
  EditCase(
    "xml preserve body indent",
    CodeLanguage.xml,
    "<note>\n  value¦",
    enter,
    "<note>\n  value\n  ¦",
  ),
  EditCase(
    "xml selected lines tab",
    CodeLanguage.xml,
    "«first\nsecond»",
    tab,
    "  «first\n  second»",
  ),
  EditCase(
    "xml selected lines outdent",
    CodeLanguage.xml,
    "  «first\n  second»",
    backtab,
    "«first\nsecond»",
  ),
  EditCase(
    "sql Enter header",
    CodeLanguage.sql,
    "SELECT COALESCE(¦",
    enter,
    "SELECT COALESCE(\n  ¦",
  ),
  EditCase(
    "sql typed closer",
    CodeLanguage.sql,
    "SELECT COALESCE(\n  ¦",
    type,
    "SELECT COALESCE(\n)¦",
    text: ")",
  ),
  EditCase(
    "sql complete literal",
    CodeLanguage.sql,
    "SELECT '{'¦",
    enter,
    "SELECT '{'\n¦",
  ),
  EditCase(
    "sql preserve body indent",
    CodeLanguage.sql,
    "SELECT COALESCE(\n  value¦",
    enter,
    "SELECT COALESCE(\n  value\n  ¦",
  ),
  EditCase(
    "sql selected lines tab",
    CodeLanguage.sql,
    "«first\nsecond»",
    tab,
    "  «first\n  second»",
  ),
  EditCase(
    "sql selected lines outdent",
    CodeLanguage.sql,
    "  «first\n  second»",
    backtab,
    "«first\nsecond»",
  ),
  EditCase("html <br>¦", CodeLanguage.html, "<br>¦", enter, "<br>\n¦"),
  EditCase(
    "html <img src=\"x\">¦",
    CodeLanguage.html,
    "<img src=\"x\">¦",
    enter,
    "<img src=\"x\">\n¦",
  ),
  EditCase(
    "html <DIV>¦</DIV>",
    CodeLanguage.html,
    "<DIV>¦</DIV>",
    enter,
    "<DIV>\n  ¦\n</DIV>",
  ),
  EditCase("xml <note/>¦", CodeLanguage.xml, "<note/>¦", enter, "<note/>\n¦"),
  EditCase(
    "xml <note>¦</note>",
    CodeLanguage.xml,
    "<note>¦</note>",
    enter,
    "<note>\n  ¦\n</note>",
  ),
  EditCase(
    "bash for x in items; do¦",
    CodeLanguage.bash,
    "for x in items; do¦",
    enter,
    "for x in items; do\n  ¦",
  ),
  EditCase(
    "bash case \"\$x\" in¦",
    CodeLanguage.bash,
    "case \"\$x\" in¦",
    enter,
    "case \"\$x\" in\n  ¦",
  ),
  EditCase(
    "bash if ready; then\nelse¦",
    CodeLanguage.bash,
    "if ready; then\nelse¦",
    enter,
    "if ready; then\nelse\n  ¦",
  ),
  EditCase("Ruby method", r, "def hello¦", enter, "def hello\n  ¦"),
  EditCase(
    "Ruby singleton method",
    r,
    "def self.hello¦",
    enter,
    "def self.hello\n  ¦",
  ),
  EditCase(
    "Ruby parameters",
    r,
    "def hello(name)¦",
    enter,
    "def hello(name)\n  ¦",
  ),
  EditCase("Ruby class", r, "class Hello¦", enter, "class Hello\n  ¦"),
  EditCase(
    "Ruby singleton class",
    r,
    "class << self¦",
    enter,
    "class << self\n  ¦",
  ),
  EditCase("Ruby module", r, "module Hello¦", enter, "module Hello\n  ¦"),
  EditCase("Ruby if", r, "if ready¦", enter, "if ready\n  ¦"),
  EditCase("Ruby unless", r, "unless ready¦", enter, "unless ready\n  ¦"),
  EditCase("Ruby while", r, "while ready¦", enter, "while ready\n  ¦"),
  EditCase("Ruby until", r, "until ready¦", enter, "until ready\n  ¦"),
  EditCase("Ruby for", r, "for x in items¦", enter, "for x in items\n  ¦"),
  EditCase("Ruby begin", r, "begin¦", enter, "begin\n  ¦"),
  EditCase("Ruby case", r, "case value¦", enter, "case value\n  ¦"),
  EditCase(
    "Ruby do block",
    r,
    "items.each do |x|¦",
    enter,
    "items.each do |x|\n  ¦",
  ),
  EditCase("Ruby while do", r, "while ready do¦", enter, "while ready do\n  ¦"),
  EditCase(
    "Ruby owner method with existing end",
    r,
    "def hello¦\nend",
    enter,
    "def hello\n  ¦\nend",
  ),
  EditCase(
    "Ruby nested method",
    r,
    "class Hello\n  def hello¦",
    enter,
    "class Hello\n  def hello\n    ¦",
  ),
  EditCase(
    "Ruby header comment",
    r,
    "def hello # comment¦",
    enter,
    "def hello # comment\n  ¦",
  ),
  EditCase(
    "Ruby body continuation",
    r,
    "def hello\n  print 'test'¦",
    enter,
    "def hello\n  print 'test'\n  ¦",
  ),
  EditCase(
    "Ruby closed one-line block",
    r,
    "if ready then run end¦",
    enter,
    "if ready then run end\n¦",
  ),
  EditCase(
    "Ruby endless method",
    r,
    "def hello = 1¦",
    enter,
    "def hello = 1\n¦",
  ),
  EditCase(
    "Ruby endless method with params",
    r,
    "def hello(name) = name¦",
    enter,
    "def hello(name) = name\n¦",
  ),
  EditCase("Ruby postfix if", r, "run if ready¦", enter, "run if ready\n¦"),
  EditCase(
    "Ruby postfix unless",
    r,
    "run unless ready¦",
    enter,
    "run unless ready\n¦",
  ),
  EditCase(
    "Ruby postfix while",
    r,
    "run while ready¦",
    enter,
    "run while ready\n¦",
  ),
  EditCase(
    "Ruby postfix until",
    r,
    "run until ready¦",
    enter,
    "run until ready\n¦",
  ),
  EditCase(
    "Ruby postfix rescue",
    r,
    "run rescue ready¦",
    enter,
    "run rescue ready\n¦",
  ),
  EditCase(
    "Ruby else body",
    r,
    "if ready\nelse¦",
    enter,
    "if ready\nelse\n  ¦",
  ),
  EditCase(
    "Ruby elsif other body",
    r,
    "if ready\nelsif other¦",
    enter,
    "if ready\nelsif other\n  ¦",
  ),
  EditCase(
    "Ruby when 1 body",
    r,
    "case value\nwhen 1¦",
    enter,
    "case value\nwhen 1\n  ¦",
  ),
  EditCase(
    "Ruby rescue Error body",
    r,
    "begin\nrescue Error¦",
    enter,
    "begin\nrescue Error\n  ¦",
  ),
  EditCase(
    "Ruby ensure body",
    r,
    "begin\nensure¦",
    enter,
    "begin\nensure\n  ¦",
  ),
  EditCase(
    "Ruby rescue Error body",
    r,
    "def hello\nrescue Error¦",
    enter,
    "def hello\nrescue Error\n  ¦",
  ),
  EditCase(
    "Ruby in [x] body",
    r,
    "case value\nin [x]¦",
    enter,
    "case value\nin [x]\n  ¦",
  ),
  EditCase(
    "Ruby typed end",
    r,
    "def hello\n  run\n  en¦",
    type,
    "def hello\n  run\nend¦",
    text: "d",
  ),
  EditCase(
    "Ruby typed else",
    r,
    "if ready\n  run\n  els¦",
    type,
    "if ready\n  run\nelse¦",
    text: "e",
  ),
  EditCase(
    "Ruby typed elsif",
    r,
    "if ready\n  run\n  elsi¦",
    type,
    "if ready\n  run\nelsif¦",
    text: "f",
  ),
  EditCase(
    "Ruby typed rescue",
    r,
    "begin\n  run\n  rescu¦",
    type,
    "begin\n  run\nrescue¦",
    text: "e",
  ),
  EditCase(
    "Ruby typed ensure",
    r,
    "begin\n  run\n  ensur¦",
    type,
    "begin\n  run\nensure¦",
    text: "e",
  ),
  EditCase(
    "Ruby typed when",
    r,
    "case value\n  run\n  whe¦",
    type,
    "case value\n  run\nwhen¦",
    text: "n",
  ),
  EditCase(
    "Ruby nested typed end",
    r,
    "class Hello\n  def hello\n    run\n    en¦",
    type,
    "class Hello\n  def hello\n    run\n  end¦",
    text: "d",
  ),
  EditCase(
    "Ruby unindented body still pairs end",
    r,
    "def hello\nrun\n  en¦",
    type,
    "def hello\nrun\nend¦",
    text: "d",
  ),
  EditCase(
    "Ruby identifier is not end",
    r,
    "def hello\n  fri en¦",
    type,
    "def hello\n  fri end¦",
    text: "d",
  ),
  EditCase(
    "Ruby identifier suffix is not end",
    r,
    "def hello\n  friend¦",
    type,
    "def hello\n  friendd¦",
    text: "d",
  ),
  EditCase(
    "Ruby comment keyword",
    r,
    "def hello\n  # en¦",
    type,
    "def hello\n  # end¦",
    text: "d",
  ),
  EditCase(
    "Ruby string keyword",
    r,
    "def hello\n  s = 'en¦'",
    type,
    "def hello\n  s = 'end¦'",
    text: "d",
  ),
  EditCase(
    "Ruby string header",
    r,
    "s = 'def hello¦'",
    enter,
    "s = 'def hello\n¦'",
  ),
  EditCase(
    "Ruby unfinished string",
    r,
    "s = 'def hello¦",
    enter,
    "s = 'def hello\n¦",
  ),
  EditCase(
    "Ruby heredoc header literal",
    r,
    "s = <<~RUBY\n  def hello¦\nRUBY",
    enter,
    "s = <<~RUBY\n  def hello\n  ¦\nRUBY",
  ),
  EditCase(
    "Ruby heredoc keyword",
    r,
    "def hello\n  s = <<~RUBY\n    en¦\nRUBY",
    type,
    "def hello\n  s = <<~RUBY\n    end¦\nRUBY",
    text: "d",
  ),
  EditCase(
    "Ruby regex punctuation",
    r,
    "def hello\n  r = /[{}]/¦",
    enter,
    "def hello\n  r = /[{}]/\n  ¦",
  ),
  EditCase(
    "Ruby brace block",
    r,
    "items.each { |x|¦}",
    enter,
    "items.each { |x|\n  ¦\n}",
  ),
  EditCase(
    "Ruby unicode and CRLF",
    r,
    "def café(name)¦",
    enter,
    "def café(name)\r\n  ¦",
    newline: "\r\n",
  ),
  EditCase(
    "Ruby tabbed end",
    r,
    "def hello\n\ten¦",
    type,
    "def hello\nend¦",
    text: "d",
    unit: "\t",
  ),
  EditCase(
    "Ruby multi character insertion is literal",
    r,
    "def hello\n  ¦",
    type,
    "def hello\n  end¦",
    text: "end",
  ),
  EditCase(
    'Python branch condition closer waits for colon',
    p,
    'if ready:\n    run()\n    elif check(¦',
    type,
    'if ready:\n    run()\n    elif check()¦',
    text: ')',
    unit: '    ',
  ),
  EditCase(
    'YAML Enter before existing value',
    y,
    'settings:¦ value',
    enter,
    'settings:\n  ¦ value',
  ),
  EditCase(
    'Python colon within branch expression',
    p,
    'if ready:\n    run()\n    elif {"x"¦ 1}',
    type,
    'if ready:\n    run()\n    elif {"x":¦ 1}',
    text: ':',
    unit: '    ',
  ),
  EditCase(
    'Dart raw literal',
    d,
    'void f() {\n  print(r"{");¦\n}',
    enter,
    'void f() {\n  print(r"{");\n  ¦\n}',
  ),
  EditCase(
    'Dart interpolation expression',
    d,
    'void f() {\n  print("\${f({¦})}");\n}',
    enter,
    'void f() {\n  print("\${f({\n    ¦\n  })}");\n}',
  ),
  EditCase(
    'Dart declaration context retained',
    d,
    'class X {¦}',
    enter,
    'class X {\n  ¦\n}',
  ),
  EditCase(
    'Dart return map fragment',
    d,
    'return {¦};',
    enter,
    'return {\n  ¦\n};',
  ),
  EditCase(
    'Python case header',
    p,
    'match x:\n    case 1:¦',
    enter,
    'match x:\n    case 1:\n        ¦',
    unit: '    ',
  ),
  EditCase(
    'Python f-string expression',
    p,
    's = f"{f({¦})}"',
    enter,
    's = f"{f({\n    ¦\n})}"',
    unit: '    ',
  ),
  EditCase(
    'Python tabbed branch alignment',
    p,
    'if ready:\n\trun()\n\telse¦',
    type,
    'if ready:\n\trun()\nelse:¦',
    unit: '\t',
    text: ':',
  ),
  EditCase(
    'Python selected colon replacement',
    p,
    'if ready:\n    run()\n    else«old»',
    type,
    'if ready:\n    run()\nelse:¦',
    unit: '    ',
    text: ':',
  ),
  EditCase(
    'Python quoted branch',
    p,
    's = """if ready:\n    else¦\n"""',
    type,
    's = """if ready:\n    else:¦\n"""',
    text: ':',
    unit: '    ',
  ),
  EditCase(
    'YAML mapping comment',
    y,
    'settings: # options¦',
    enter,
    'settings: # options\n  ¦',
  ),
  EditCase(
    'YAML finished value preserves indent',
    y,
    '  value: one¦',
    enter,
    '  value: one\n  ¦',
  ),
  EditCase('YAML unfinished quote', y, 'value: "{¦', enter, 'value: "{\n¦'),
  EditCase(
    'YAML folded body angle bracket',
    y,
    'settings: >\n  text >¦',
    enter,
    'settings: >\n  text >\n  ¦',
  ),
  EditCase(
    'YAML existing scalar body begins at caret',
    y,
    'settings: |¦\n  body',
    enter,
    'settings: |\n  ¦\n  body',
  ),
  EditCase(
    'empty line retains exact mixed indent',
    j,
    ' \t ¦',
    enter,
    ' \t \n \t ¦',
  ),
  EditCase('unmatched closer leaves indent', j, '  ¦', type, '  }¦', text: '}'),
  EditCase(
    'nested closer skips string and comment brackets',
    j,
    'if (x) {\n  f("}"); // }\n  ¦',
    type,
    'if (x) {\n  f("}"); // }\n}¦',
    text: '}',
  ),
  EditCase(
    'owner Dart loop Enter',
    d,
    'for (final x in [1,2,3]) {¦',
    enter,
    'for (final x in [1,2,3]) {\n  ¦',
  ),
  EditCase(
    'owner Dart typed brace',
    d,
    'for (final x in [1,2,3]) {\n  ¦',
    type,
    'for (final x in [1,2,3]) {\n}¦',
    text: '}',
  ),
  EditCase('Dart paired Enter', d, 'void f() {¦}', enter, 'void f() {\n  ¦\n}'),
  EditCase(
    'Dart paired Enter trims right space',
    d,
    'void f() {¦  }',
    enter,
    'void f() {\n  ¦\n}',
  ),
  EditCase(
    'Dart nested brace',
    d,
    'void f() {\n  if (ready) {\n    ¦',
    type,
    'void f() {\n  if (ready) {\n  }¦',
    text: '}',
  ),
  EditCase(
    'Dart literal brace',
    d,
    'void f() {\n  print("{");¦\n}',
    enter,
    'void f() {\n  print("{");\n  ¦\n}',
  ),
  EditCase(
    'Dart unfinished quote',
    d,
    'void f() {\n  print("{¦',
    enter,
    'void f() {\n  print("{\n  ¦',
  ),
  EditCase(
    'Dart unfinished block comment',
    d,
    'void f() {\n  /* {¦',
    enter,
    'void f() {\n  /* {\n  ¦',
  ),
  EditCase(
    'Dart closer inside unfinished comment',
    d,
    'void f() {\n  /* note\n    ¦',
    type,
    'void f() {\n  /* note\n    }¦',
    text: '}',
  ),
  EditCase(
    'Dart trailing comment after opener',
    d,
    'void f() { // note¦',
    enter,
    'void f() { // note\n  ¦',
  ),
  EditCase(
    'Dart closed block comment after opener',
    d,
    'void f() { /* note */¦',
    enter,
    'void f() { /* note */\n  ¦',
  ),
  EditCase(
    'Dart newline after ordinary statement',
    d,
    'void f() {\n  run();¦\n}',
    enter,
    'void f() {\n  run();\n  ¦\n}',
  ),
  EditCase(
    'Dart no staircase inside list',
    d,
    'final xs = [\n  1,¦',
    enter,
    'final xs = [\n  1,\n  ¦',
  ),
  EditCase(
    'Dart list closer',
    d,
    'final xs = [\n  1,\n  ¦',
    type,
    'final xs = [\n  1,\n]¦',
    text: ']',
  ),
  EditCase(
    'Dart literal multi-character insertion',
    d,
    'void f() {\n  ¦',
    type,
    'void f() {\n  } // paste¦',
    text: '} // paste',
  ),
  EditCase(
    'Dart brace replaces selection',
    d,
    'void f() {\n  «old»',
    type,
    'void f() {\n}¦',
    text: '}',
  ),
  EditCase(
    'Dart Enter replaces multiline selection',
    d,
    'void f() {«old\ntext»}',
    enter,
    'void f() {\n  ¦\n}',
  ),
  EditCase(
    'Dart midline Enter',
    d,
    'void f() {¦run();}',
    enter,
    'void f() {\n  ¦run();}',
  ),
  EditCase(
    'Dart tabs and CRLF',
    d,
    'void f() {\r\n\tif (ready) {¦',
    enter,
    'void f() {\r\n\tif (ready) {\r\n\t\t¦',
    unit: '\t',
    newline: '\r\n',
  ),
  EditCase(
    'Dart Unicode before edit',
    d,
    'void f() {\n  print("😀 café");\n  ¦',
    type,
    'void f() {\n  print("😀 café");\n}¦',
    text: '}',
  ),
  EditCase('JS Enter', j, 'if (ready) {¦', enter, 'if (ready) {\n  ¦'),
  EditCase(
    'JS brace outdent',
    j,
    'if (ready) {\n  ¦',
    type,
    'if (ready) {\n}¦',
    text: '}',
  ),
  EditCase(
    'JS regex braces',
    j,
    'const x = /[{}]/;¦',
    enter,
    'const x = /[{}]/;\n¦',
  ),
  EditCase(
    'JS unfinished block comment',
    j,
    'if (ready) {\n  /* {¦',
    enter,
    'if (ready) {\n  /* {\n  ¦',
  ),
  EditCase(
    'JS unfinished quote',
    j,
    'if (ready) {\n  const s = "{¦',
    enter,
    'if (ready) {\n  const s = "{\n  ¦',
  ),
  EditCase(
    'JS template text',
    j,
    'const s = `hello\n  ¦`; ',
    type,
    'const s = `hello\n  }¦`; ',
    text: '}',
  ),
  EditCase(
    'JS template expression',
    j,
    'const s = `hello \${f({¦})}`;',
    enter,
    'const s = `hello \${f({\n  ¦\n})}`;',
  ),
  EditCase('JS argument continuation', j, 'f(one,¦', enter, 'f(one,\n  ¦'),
  EditCase(
    'JS mismatched closer preserves whitespace',
    j,
    'f([\n  ¦',
    type,
    'f([\n  }¦',
    text: '}',
  ),
  EditCase(
    'Python if Enter',
    p,
    'if ready:¦',
    enter,
    'if ready:\n    ¦',
    unit: '    ',
  ),
  EditCase(
    'Python else aligns',
    p,
    'if ready:\n    run()\n    else¦',
    type,
    'if ready:\n    run()\nelse:¦',
    text: ':',
    unit: '    ',
  ),
  EditCase(
    'Python else Enter',
    p,
    'if ready:\n    run()\nelse:¦',
    enter,
    'if ready:\n    run()\nelse:\n    ¦',
    unit: '    ',
  ),
  EditCase(
    'Python elif aligns',
    p,
    'if ready:\n    run()\n    elif other¦',
    type,
    'if ready:\n    run()\nelif other:¦',
    text: ':',
    unit: '    ',
  ),
  EditCase(
    'Python nested else',
    p,
    'if outer:\n    if inner:\n        run()\n        else¦',
    type,
    'if outer:\n    if inner:\n        run()\n    else:¦',
    text: ':',
    unit: '    ',
  ),
  EditCase(
    'Python loop else',
    p,
    'for x in xs:\n    run()\n    else¦',
    type,
    'for x in xs:\n    run()\nelse:¦',
    text: ':',
    unit: '    ',
  ),
  EditCase(
    'Python except aligns',
    p,
    'try:\n    run()\n    except Error¦',
    type,
    'try:\n    run()\nexcept Error:¦',
    text: ':',
    unit: '    ',
  ),
  EditCase(
    'Python finally aligns',
    p,
    'try:\n    run()\nexcept Error:\n    recover()\n    finally¦',
    type,
    'try:\n    run()\nexcept Error:\n    recover()\nfinally:¦',
    text: ':',
    unit: '    ',
  ),
  EditCase(
    'Python stale if does not align else',
    p,
    'if ready:\n    run()\nfinished()\n    else¦',
    type,
    'if ready:\n    run()\nfinished()\n    else:¦',
    text: ':',
    unit: '    ',
  ),
  EditCase('Python try Enter', p, 'try:¦', enter, 'try:\n    ¦', unit: '    '),
  EditCase(
    'Python def Enter',
    p,
    'def f():¦',
    enter,
    'def f():\n    ¦',
    unit: '    ',
  ),
  EditCase(
    'Python trailing comment',
    p,
    'if ready: # note¦',
    enter,
    'if ready: # note\n    ¦',
    unit: '    ',
  ),
  EditCase(
    'Python string colon',
    p,
    'print("if ready:")¦',
    enter,
    'print("if ready:")\n¦',
    unit: '    ',
  ),
  EditCase(
    'Python lambda colon',
    p,
    'f = lambda x:¦',
    enter,
    'f = lambda x:\n¦',
    unit: '    ',
  ),
  EditCase(
    'Python dict continuation',
    p,
    'x = {"key": 1,¦',
    enter,
    'x = {"key": 1,\n    ¦',
    unit: '    ',
  ),
  EditCase(
    'Python unfinished triple string',
    p,
    'def f():\n    """abc\n    {¦',
    enter,
    'def f():\n    """abc\n    {\n    ¦',
    unit: '    ',
  ),
  EditCase(
    'Python multiline literal closer',
    p,
    's = """hello\n    ¦\n"""',
    type,
    's = """hello\n    }¦\n"""',
    text: '}',
    unit: '    ',
  ),
  EditCase('YAML empty mapping', y, 'settings:¦', enter, 'settings:\n  ¦'),
  EditCase('YAML block scalar', y, 'settings: |¦', enter, 'settings: |\n  ¦'),
  EditCase(
    'YAML folded scalar comment',
    y,
    'settings: >- # note¦',
    enter,
    'settings: >- # note\n  ¦',
  ),
  EditCase(
    'YAML explicit scalar indentation',
    y,
    'settings: |4¦',
    enter,
    'settings: |4\n    ¦',
  ),
  EditCase(
    'YAML scalar body braces',
    y,
    'settings: |\n  {¦',
    enter,
    'settings: |\n  {\n  ¦',
  ),
  EditCase(
    'YAML scalar body closer',
    y,
    'settings: |\n  {\n    ¦',
    type,
    'settings: |\n  {\n    }¦',
    text: '}',
  ),
  EditCase(
    'YAML sequence mapping',
    y,
    'items:\n  - name:¦',
    enter,
    'items:\n  - name:\n      ¦',
  ),
  EditCase(
    'YAML URL',
    y,
    'url: https://example.com¦',
    enter,
    'url: https://example.com\n¦',
  ),
  EditCase(
    'YAML plain scalar punctuation',
    y,
    'value: ordinary {¦',
    enter,
    'value: ordinary {\n¦',
  ),
  EditCase('YAML quoted punctuation', y, 'value: "{"¦', enter, 'value: "{"\n¦'),
  EditCase(
    'YAML flow paired Enter',
    y,
    'value: {¦}',
    enter,
    'value: {\n  ¦\n}',
  ),
  EditCase(
    'plain language baseline',
    CodeLanguage.plain,
    '  text {¦',
    enter,
    '  text {\n  ¦',
  ),
  EditCase('Tab inserts unit', d, 'a¦b', tab, 'a  ¦b'),
  EditCase('Shift Tab removes spaces', d, '  ¦x', backtab, '¦x'),
  EditCase('Shift Tab removes partial unit', d, ' ¦x', backtab, '¦x'),
  EditCase('Shift Tab removes tab', d, '\t¦x', backtab, '¦x', unit: '\t'),
  EditCase(
    'Tab selected lines excludes end line',
    d,
    '«one\ntwo\n»three',
    tab,
    '  «one\n  two\n»three',
  ),
  EditCase(
    'Shift Tab preserves reverse selection',
    d,
    '  »one\n  two«',
    backtab,
    '»one\ntwo«',
  ),
  EditCase(
    'Tab blank lines CRLF Unicode',
    d,
    '«😀\r\n\r\nx»',
    tab,
    '  «😀\r\n  \r\n  x»',
    newline: '\r\n',
  ),
];

({String source, int base, int extent}) marked(String value) {
  final caret = value.indexOf('¦');
  if (caret >= 0) {
    return (source: value.replaceFirst('¦', ''), base: caret, extent: caret);
  }
  final base = value.indexOf('«'), extent = value.indexOf('»');
  if (base < 0 || extent < 0) throw StateError('Missing selection marker');
  return (
    source: value.replaceAll('«', '').replaceAll('»', ''),
    base: base - (extent < base ? 1 : 0),
    extent: extent - (base < extent ? 1 : 0),
  );
}

Map<String, Object> runEditCase(CodeAnalyzer analyzer, EditCase c) {
  final before = marked(c.before), after = marked(c.after);
  final edit = analyzer.proposeEdit(
    before.source,
    language: c.language,
    base: before.base,
    extent: before.extent,
    action: c.action,
    text: c.text,
    indentUnit: c.unit,
    newline: c.newline,
  )!;
  final source = edit.applyTo(before.source);
  if (source != after.source ||
      edit.base != after.base ||
      edit.extent != after.extent) {
    throw StateError(
      '${c.name}: expected ${after.source} @ ${after.base},${after.extent}; got $source @ ${edit.base},${edit.extent}',
    );
  }
  // Verify the next typed character lands at the promised selection.
  final next = analyzer.proposeEdit(
    source,
    language: c.language,
    base: edit.base,
    extent: edit.extent,
    action: type,
    text: 'z',
    indentUnit: c.unit,
    newline: c.newline,
  )!;
  final lo = after.base < after.extent ? after.base : after.extent;
  final hi = after.base > after.extent ? after.base : after.extent;
  if (next.applyTo(source) != after.source.replaceRange(lo, hi, 'z') ||
      next.base != lo + 1 ||
      next.extent != lo + 1) {
    throw StateError('${c.name}: following character violated selection');
  }
  return {
    'name': c.name,
    'source': source,
    'base': edit.base,
    'extent': edit.extent,
    'replacement': [edit.start, edit.end, edit.text],
    'following': next.applyTo(source),
  };
}
