/* Generated by re2rust 4.3.1 */
// Generated with:
// re2rust 4.3.1 --no-generation-date --storable-state \
//   -o src/atx_generated.rs rules/atx.re
//
// Do not add Markdown syntax here. generate.py inserts the exact ATX pattern
// extracted from the pinned Comrak scanners.re source.

/// Result of one resumable scanner poll.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ScanResult {
    /// The scanner reached the current source grant and saved exact DFA state.
    NeedMore,
    /// The scanner accepted the ATX prefix and reports the donor byte count.
    Matched(usize),
    /// The input cannot match the ATX rule.
    NoMatch,
}

/// A proof-only source window around a generated storable DFA.
///
/// The complete byte vector stands in for a Crop-backed random-access cursor;
/// `available` is the only prefix the generated scanner is allowed to inspect.
pub struct AtxScanner {
    yyinput: Vec<u8>,
    source_len: usize,
    available: usize,
    yylimit: usize,
    yycursor: usize,
    yymarker: usize,
    yystate: isize,
}

impl AtxScanner {
    /// Creates a scanner with no source bytes granted yet.
    #[must_use]
    pub fn new(source: &[u8]) -> Self {
        assert!(!source.contains(&0xff), "UTF-8 source cannot contain 0xff");
        let mut yyinput = source.to_vec();
        yyinput.extend([0xff; YYMAXFILL]);
        Self {
            yyinput,
            source_len: source.len(),
            available: 0,
            yylimit: 0,
            yycursor: 0,
            yymarker: 0,
            yystate: -1,
        }
    }

    /// Grants at most `bytes` additional source bytes, then resumes the DFA.
    pub fn poll(&mut self, bytes: usize) -> ScanResult {
        self.available = self.available.saturating_add(bytes).min(self.source_len);
        // YYMAXFILL fake sentinels become visible only after every real byte
        // has been granted. Before then YYFILL suspends with exact DFA state.
        self.yylimit = if self.available == self.source_len {
            self.source_len + YYMAXFILL
        } else {
            self.available
        };
        scan(self)
    }

    /// Returns the number of source bytes inspected or skipped by the DFA.
    #[must_use]
    pub fn cursor(&self) -> usize {
        self.yycursor.min(self.source_len)
    }
}

fn scan(yyrecord: &mut AtxScanner) -> ScanResult {
    let mut yych;

    {
        let mut yystate: isize = yyrecord.yystate;
        'yyl: loop {
            match yystate {
                -1..=0 => {
                    if (yyrecord.yylimit - yyrecord.yycursor) < 7 {
                        yyrecord.yystate = 13;
                        return ScanResult::NeedMore;
                    }
                    yych = unsafe { *yyrecord.yyinput.get_unchecked(yyrecord.yycursor) };
                    yyrecord.yycursor += 1;
                    match yych {
                        0x23 => {
                            yystate = 3;
                            continue 'yyl;
                        }
                        _ => {
                            yystate = 1;
                            continue 'yyl;
                        }
                    }
                }
                1 => {
                    yystate = 2;
                    continue 'yyl;
                }
                2 => {
                    yyrecord.yystate = -1;
                    {
                        return ScanResult::NoMatch;
                    }
                }
                3 => {
                    yyrecord.yymarker = yyrecord.yycursor;
                    yych = unsafe { *yyrecord.yyinput.get_unchecked(yyrecord.yycursor) };
                    match yych {
                        0x00..=0x08 | 0x0B..=0x0C | 0x0E..=0x1F | 0x21..=0x22 | 0x24..=0xFE => {
                            yystate = 2;
                            continue 'yyl;
                        }
                        0x09 | 0x20 => {
                            yyrecord.yycursor += 1;
                            yystate = 4;
                            continue 'yyl;
                        }
                        0x23 => {
                            yyrecord.yycursor += 1;
                            yystate = 7;
                            continue 'yyl;
                        }
                        _ => {
                            yyrecord.yycursor += 1;
                            yystate = 6;
                            continue 'yyl;
                        }
                    }
                }
                4 => {
                    if yyrecord.yylimit <= yyrecord.yycursor {
                        yyrecord.yystate = 14;
                        return ScanResult::NeedMore;
                    }
                    yych = unsafe { *yyrecord.yyinput.get_unchecked(yyrecord.yycursor) };
                    match yych {
                        0x09 | 0x20 => {
                            yyrecord.yycursor += 1;
                            yystate = 4;
                            continue 'yyl;
                        }
                        _ => {
                            yystate = 5;
                            continue 'yyl;
                        }
                    }
                }
                5 => {
                    yyrecord.yystate = -1;
                    {
                        return ScanResult::Matched(yyrecord.yycursor.min(yyrecord.source_len));
                    }
                }
                6 => {
                    yystate = 5;
                    continue 'yyl;
                }
                7 => {
                    yych = unsafe { *yyrecord.yyinput.get_unchecked(yyrecord.yycursor) };
                    match yych {
                        0x00..=0x08 | 0x0B..=0x0C | 0x0E..=0x1F | 0x21..=0x22 | 0x24..=0xFE => {
                            yystate = 8;
                            continue 'yyl;
                        }
                        0x09 | 0x20 => {
                            yyrecord.yycursor += 1;
                            yystate = 4;
                            continue 'yyl;
                        }
                        0x23 => {
                            yyrecord.yycursor += 1;
                            yystate = 9;
                            continue 'yyl;
                        }
                        _ => {
                            yyrecord.yycursor += 1;
                            yystate = 6;
                            continue 'yyl;
                        }
                    }
                }
                8 => {
                    yyrecord.yycursor = yyrecord.yymarker;
                    yystate = 2;
                    continue 'yyl;
                }
                9 => {
                    yych = unsafe { *yyrecord.yyinput.get_unchecked(yyrecord.yycursor) };
                    match yych {
                        0x00..=0x08 | 0x0B..=0x0C | 0x0E..=0x1F | 0x21..=0x22 | 0x24..=0xFE => {
                            yystate = 8;
                            continue 'yyl;
                        }
                        0x09 | 0x20 => {
                            yyrecord.yycursor += 1;
                            yystate = 4;
                            continue 'yyl;
                        }
                        0x23 => {
                            yyrecord.yycursor += 1;
                            yystate = 10;
                            continue 'yyl;
                        }
                        _ => {
                            yyrecord.yycursor += 1;
                            yystate = 6;
                            continue 'yyl;
                        }
                    }
                }
                10 => {
                    yych = unsafe { *yyrecord.yyinput.get_unchecked(yyrecord.yycursor) };
                    match yych {
                        0x00..=0x08 | 0x0B..=0x0C | 0x0E..=0x1F | 0x21..=0x22 | 0x24..=0xFE => {
                            yystate = 8;
                            continue 'yyl;
                        }
                        0x09 | 0x20 => {
                            yyrecord.yycursor += 1;
                            yystate = 4;
                            continue 'yyl;
                        }
                        0x23 => {
                            yyrecord.yycursor += 1;
                            yystate = 11;
                            continue 'yyl;
                        }
                        _ => {
                            yyrecord.yycursor += 1;
                            yystate = 6;
                            continue 'yyl;
                        }
                    }
                }
                11 => {
                    yych = unsafe { *yyrecord.yyinput.get_unchecked(yyrecord.yycursor) };
                    match yych {
                        0x00..=0x08 | 0x0B..=0x0C | 0x0E..=0x1F | 0x21..=0x22 | 0x24..=0xFE => {
                            yystate = 8;
                            continue 'yyl;
                        }
                        0x09 | 0x20 => {
                            yyrecord.yycursor += 1;
                            yystate = 4;
                            continue 'yyl;
                        }
                        0x23 => {
                            yyrecord.yycursor += 1;
                            yystate = 12;
                            continue 'yyl;
                        }
                        _ => {
                            yyrecord.yycursor += 1;
                            yystate = 6;
                            continue 'yyl;
                        }
                    }
                }
                12 => {
                    yych = unsafe { *yyrecord.yyinput.get_unchecked(yyrecord.yycursor) };
                    match yych {
                        0x00..=0x08 | 0x0B..=0x0C | 0x0E..=0x1F | 0x21..=0xFE => {
                            yystate = 8;
                            continue 'yyl;
                        }
                        0x09 | 0x20 => {
                            yyrecord.yycursor += 1;
                            yystate = 4;
                            continue 'yyl;
                        }
                        _ => {
                            yyrecord.yycursor += 1;
                            yystate = 6;
                            continue 'yyl;
                        }
                    }
                }
                13 => {
                    yystate = 0;
                    continue 'yyl;
                }
                14 => {
                    yystate = 4;
                    continue 'yyl;
                }
                _ => panic!("internal lexer error"),
            }
        }
    }
}

const YYMAXFILL: usize = 7;
