import 'dart:io';

import 'flark_wasm_buildinfo.dart';

/// Regenerates the source manifest beside both staged WASM copies.
///
/// The root package remains the build authority. `scripts/build_comrak_wasm.sh`
/// invokes this immediately after staging its binary in the root package and
/// the official Flutter adapter, so both artifacts carry the same freshness
/// receipt.
void main() {
  final packageRoot = File.fromUri(Platform.script).parent.parent;
  final crateDir = Directory('${packageRoot.path}/native/comrak_bridge');
  if (!crateDir.existsSync()) {
    stderr.writeln('Cannot find crate at ${crateDir.path}');
    exitCode = 1;
    return;
  }

  final manifest = flarkWasmBuildInfo(crateDir);
  final outputs = [
    File(
      '${packageRoot.path}/lib/assets/wasm/'
      'flark_comrak_bridge.wasm.buildinfo',
    ),
    File(
      '${packageRoot.path}/packages/flark_flutter/lib/assets/wasm/'
      'flark_comrak_bridge.wasm.buildinfo',
    ),
  ];
  for (final output in outputs) {
    output.parent.createSync(recursive: true);
    output.writeAsStringSync(manifest);
  }

  final assetVersion = flarkV3WebAssetVersion(
    wasm: File('${packageRoot.path}/lib/assets/wasm/flark_comrak_bridge.wasm'),
    wasmBuildinfo: outputs.first,
    worker: File(
      '${packageRoot.path}/lib/assets/worker/flark_v3_parser_worker.js',
    ),
  );
  final versionOutput = File(
    '${packageRoot.path}/example/lib/'
    'v3_engine_lab_web_asset_version.dart',
  );
  versionOutput.writeAsStringSync(
    '// GENERATED CODE - DO NOT MODIFY BY HAND.\n'
    '// Generated by `dart run tool/gen_wasm_buildinfo.dart`.\n\n'
    'const String v3EngineLabWebAssetVersion =\n'
    "    '$assetVersion';\n",
  );

  final inputCount = manifest.split('\n').where((l) => l.isNotEmpty).length;
  for (final output in outputs) {
    stdout.writeln('Wrote ${output.path} ($inputCount inputs).');
  }
  stdout.writeln(
    'Wrote ${versionOutput.path} '
    '(v3 Web asset version $assetVersion).',
  );
}
