// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by `dart run tool/gen_wasm_buildinfo.dart`.

const String v3EngineLabWebAssetVersion =
    '2d9db6cbfc80d862-8e3e32c202d2c7cb-bba3dc0f34f51964';
