// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by `dart run tool/gen_wasm_buildinfo.dart`.

const String v3EngineLabWebAssetVersion =
    '0d10099cf9d3f6d9-ef083508e8b578de-bba3dc0f34f51964';
