// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by `dart run tool/gen_wasm_buildinfo.dart`.

const String v3EngineLabWebAssetVersion =
    'f053ecb3c204bd79-08ab34d99ae1f363-bba3dc0f34f51964';
