use flark_parser::m11_is_markdown_punctuation;

fn scalar_ranges(predicate: impl Fn(char) -> bool) -> Vec<(u32, u32)> {
    let mut ranges = Vec::new();
    let mut open: Option<(u32, u32)> = None;
    for value in 0..=0x10_FFFF {
        let matches = char::from_u32(value).is_some_and(&predicate);
        match (open, matches) {
            (None, true) => open = Some((value, value)),
            (Some((start, _)), true) => open = Some((start, value)),
            (Some(range), false) => {
                ranges.push(range);
                open = None;
            }
            (None, false) => {}
        }
    }
    if let Some(range) = open {
        ranges.push(range);
    }
    ranges
}

fn print_ranges(name: &str, ranges: &[(u32, u32)]) {
    println!("  static const List<int> {name} = <int>[");
    for &(start, end) in ranges {
        println!("    0x{start:X}, 0x{end:X},");
    }
    println!("  ];");
}

fn main() {
    println!("// GENERATED by:");
    println!("// cargo run -p flark-parser --example generate_markdown_scalar_tables");
    println!("//");
    println!("// Do not hand-edit. The parser crate exhaustively verifies these ranges");
    println!("// against the exact scalar classifiers used for delimiter flanking.");
    println!();
    println!("final class FlarkCoreMarkdownScalarTables {{");
    println!("  const FlarkCoreMarkdownScalarTables._();");
    println!();
    println!("  static bool isWhitespace(int scalar) =>");
    println!("      _contains(_whitespaceRangeBounds, scalar);");
    println!();
    println!("  static bool isPunctuationOrSymbol(int scalar) =>");
    println!("      _contains(_punctuationOrSymbolRangeBounds, scalar);");
    println!();
    println!("  static bool _contains(List<int> bounds, int scalar) {{");
    println!("    var low = 0;");
    println!("    var high = bounds.length ~/ 2;");
    println!("    while (low < high) {{");
    println!("      final middle = low + ((high - low) >> 1);");
    println!("      final start = bounds[middle * 2];");
    println!("      final end = bounds[middle * 2 + 1];");
    println!("      if (scalar < start) {{");
    println!("        high = middle;");
    println!("      }} else if (scalar > end) {{");
    println!("        low = middle + 1;");
    println!("      }} else {{");
    println!("        return true;");
    println!("      }}");
    println!("    }}");
    println!("    return false;");
    println!("  }}");
    println!();
    print_ranges(
        "_whitespaceRangeBounds",
        &scalar_ranges(char::is_whitespace),
    );
    println!();
    print_ranges(
        "_punctuationOrSymbolRangeBounds",
        &scalar_ranges(m11_is_markdown_punctuation),
    );
    println!("}}");
}
