// Generated by tool/gen_schema.py from schema/render_model_v5.json. Do not edit.
#![allow(dead_code)]

pub const VERSION: u32 = 5;
pub const MAGIC: u32 = 0x354B4C46; // 'FLK5' little-endian
pub const HEADER_WORDS: usize = 12;
pub mod header {
    pub const MAGIC: usize = 0;
    pub const VERSION: usize = 1;
    pub const SRC_BYTES: usize = 2;
    pub const SRC_UTF16: usize = 3;
    pub const LINE_COUNT: usize = 4;
    pub const BLOCK_COUNT: usize = 5;
    pub const CONTENT_COUNT: usize = 6;
    pub const RUN_COUNT: usize = 7;
    pub const DEFINITION_COUNT: usize = 8;
    pub const RUN_EXTRA_COUNT: usize = 9;
    pub const EXTRA_WORDS: usize = 10;
    pub const STRING_BYTES: usize = 11;
}
pub mod line {
    pub const WORDS: usize = 1;
    pub const START: usize = 0;
}
pub mod block {
    pub const WORDS: usize = 10;
    pub const KIND_FLAGS: usize = 0;
    pub const PARENT: usize = 1;
    pub const START: usize = 2;
    pub const END: usize = 3;
    pub const FIRST_LINE: usize = 4;
    pub const LINE_COUNT: usize = 5;
    pub const CONTENT_OFFSET: usize = 6;
    pub const FIRST_RUN: usize = 7;
    pub const ATTR: usize = 8;
    pub const EXTRA: usize = 9;
    pub mod kind_flags {
        pub const KIND_SHIFT: u32 = 0;
        pub const KIND_MASK: u32 = 0xFF;
        pub const FLAGS_SHIFT: u32 = 8;
        pub const FLAGS_MASK: u32 = 0xFFFFFF;
    }
}
pub mod content {
    pub const WORDS: usize = 4;
    pub const START: usize = 0;
    pub const END: usize = 1;
    pub const PREFIX_START: usize = 2;
    pub const LINE_VIRTUAL: usize = 3;
    pub mod line_virtual {
        pub const LINE_SHIFT: u32 = 0;
        pub const LINE_MASK: u32 = 0x3FFFFFFF;
        pub const VIRTUAL_LEADING_SPACES_SHIFT: u32 = 30;
        pub const VIRTUAL_LEADING_SPACES_MASK: u32 = 0x3;
    }
}
pub mod run {
    pub const WORDS: usize = 4;
    pub const START: usize = 0;
    pub const END: usize = 1;
    pub const HIDDEN: usize = 2;
    pub const KIND_FLAGS_PARENT: usize = 3;
    pub mod hidden {
        pub const BEFORE_SHIFT: u32 = 0;
        pub const BEFORE_MASK: u32 = 0xFFFF;
        pub const AFTER_SHIFT: u32 = 16;
        pub const AFTER_MASK: u32 = 0xFFFF;
    }
    pub mod kind_flags_parent {
        pub const KIND_SHIFT: u32 = 0;
        pub const KIND_MASK: u32 = 0xFF;
        pub const FLAGS_SHIFT: u32 = 8;
        pub const FLAGS_MASK: u32 = 0xFF;
        pub const PARENT_DISTANCE_SHIFT: u32 = 16;
        pub const PARENT_DISTANCE_MASK: u32 = 0xFFFF;
    }
}
pub mod definition {
    pub const WORDS: usize = 6;
    pub const START: usize = 0;
    pub const END: usize = 1;
    pub const LABEL_START: usize = 2;
    pub const LABEL_END: usize = 3;
    pub const DEST_START: usize = 4;
    pub const DEST_END: usize = 5;
}
pub mod run_extra {
    pub const WORDS: usize = 2;
    pub const RUN: usize = 0;
    pub const OFFSET: usize = 1;
}
pub mod extra {
    pub const NONE: u32 = 0xFFFFFFFF;
    pub mod code_block {
        pub const WORDS: usize = 2;
        pub const INFO_START: usize = 0;
        pub const INFO_END: usize = 1;
    }
    pub mod item {
        pub const WORDS: usize = 3;
        pub const MARKER_END: usize = 0;
        pub const TASK_START: usize = 1;
        pub const TASK_END: usize = 2;
    }
    pub mod table {
        pub const WORDS: usize = 1;
        pub const ALIGNMENTS: usize = 0;
    }
    pub mod footnote_definition {
        pub const WORDS: usize = 2;
        pub const LABEL_START: usize = 0;
        pub const LABEL_END: usize = 1;
    }
    pub mod wide_run {
        pub const WORDS: usize = 3;
        pub const CONTENT_START: usize = 0;
        pub const CONTENT_END: usize = 1;
        pub const PARENT: usize = 2;
    }
    pub mod link {
        pub const WORDS: usize = 8;
        pub const DESTINATION_START: usize = 0;
        pub const DESTINATION_END: usize = 1;
        pub const TITLE_START: usize = 2;
        pub const TITLE_END: usize = 3;
        pub const DESTINATION_OFFSET: usize = 4;
        pub const DESTINATION_LENGTH: usize = 5;
        pub const TITLE_OFFSET: usize = 6;
        pub const TITLE_LENGTH: usize = 7;
    }
    pub mod display_text {
        pub const WORDS: usize = 2;
        pub const OFFSET: usize = 0;
        pub const LENGTH: usize = 1;
    }
    pub mod footnote_ref {
        pub const WORDS: usize = 2;
        pub const LABEL_START: usize = 0;
        pub const LABEL_END: usize = 1;
    }
}
pub mod block_kind {
    pub const DOCUMENT: u32 = 0;
    pub const PARAGRAPH: u32 = 1;
    pub const HEADING: u32 = 2;
    pub const CODE_BLOCK: u32 = 3;
    pub const HTML_BLOCK: u32 = 4;
    pub const BLOCK_QUOTE: u32 = 5;
    pub const LIST: u32 = 6;
    pub const ITEM: u32 = 7;
    pub const THEMATIC_BREAK: u32 = 8;
    pub const TABLE: u32 = 9;
    pub const TABLE_ROW: u32 = 10;
    pub const TABLE_CELL: u32 = 11;
    pub const FOOTNOTE_DEFINITION: u32 = 12;
    pub const OTHER: u32 = 14;
}
pub mod run_kind {
    pub const TEXT: u32 = 1;
    pub const EMPH: u32 = 2;
    pub const STRONG: u32 = 3;
    pub const CODE: u32 = 4;
    pub const STRIKE: u32 = 5;
    pub const LINK: u32 = 6;
    pub const IMAGE: u32 = 7;
    pub const AUTOLINK: u32 = 8;
    pub const ESCAPE: u32 = 9;
    pub const REPLACEMENT: u32 = 10;
    pub const HARD_BREAK: u32 = 11;
    pub const SOFT_BREAK: u32 = 12;
    pub const HTML_INLINE: u32 = 13;
    pub const FOOTNOTE_REF: u32 = 14;
    pub const OTHER: u32 = 16;
}
pub mod table_alignment {
    pub const NONE: u32 = 0;
    pub const LEFT: u32 = 1;
    pub const CENTER: u32 = 2;
    pub const RIGHT: u32 = 3;
}
