// Generated by tool/gen_schema.py from schema/render_model_v1.json. Do not edit.
#![allow(dead_code)]

pub const VERSION: u32 = 1;
pub const MAGIC: u32 = 0x354B4C46; // 'FLK5' little-endian
pub const HEADER_WORDS: usize = 11;
pub mod header {
    pub const MAGIC: usize = 0;
    pub const VERSION: usize = 1;
    pub const SRC_BYTES: usize = 2;
    pub const SRC_UTF16: usize = 3;
    pub const LINE_COUNT: usize = 4;
    pub const BLOCK_COUNT: usize = 5;
    pub const CONTENT_COUNT: usize = 6;
    pub const RUN_COUNT: usize = 7;
    pub const DEFINITION_COUNT: usize = 8;
    pub const STRING_BYTES: usize = 9;
    pub const RESERVED: usize = 10;
}
pub mod line {
    pub const WORDS: usize = 2;
    pub const START_BYTE: usize = 0;
    pub const START_UTF16: usize = 1;
}
pub mod block {
    pub const WORDS: usize = 14;
    pub const KIND: usize = 0;
    pub const PARENT: usize = 1;
    pub const START_BYTE: usize = 2;
    pub const END_BYTE: usize = 3;
    pub const START_UTF16: usize = 4;
    pub const END_UTF16: usize = 5;
    pub const FIRST_LINE: usize = 6;
    pub const LINE_COUNT: usize = 7;
    pub const CONTENT_OFFSET: usize = 8;
    pub const CONTENT_COUNT: usize = 9;
    pub const ATTR0: usize = 10;
    pub const ATTR1: usize = 11;
    pub const ATTR2: usize = 12;
    pub const FLAGS: usize = 13;
}
pub mod content {
    pub const WORDS: usize = 8;
    pub const LINE: usize = 0;
    pub const START_BYTE: usize = 1;
    pub const START_UTF16: usize = 2;
    pub const END_BYTE: usize = 3;
    pub const END_UTF16: usize = 4;
    pub const VIRTUAL_LEADING_SPACES: usize = 5;
    pub const PREFIX_START_BYTE: usize = 6;
    pub const PREFIX_START_UTF16: usize = 7;
}
pub mod run {
    pub const WORDS: usize = 16;
    pub const KIND: usize = 0;
    pub const BLOCK: usize = 1;
    pub const PARENT: usize = 2;
    pub const START_BYTE: usize = 3;
    pub const END_BYTE: usize = 4;
    pub const CONTENT_START_BYTE: usize = 5;
    pub const CONTENT_END_BYTE: usize = 6;
    pub const START_UTF16: usize = 7;
    pub const END_UTF16: usize = 8;
    pub const CONTENT_START_UTF16: usize = 9;
    pub const CONTENT_END_UTF16: usize = 10;
    pub const AUX0: usize = 11;
    pub const AUX1: usize = 12;
    pub const AUX2: usize = 13;
    pub const AUX3: usize = 14;
    pub const FLAGS: usize = 15;
}
pub mod definition {
    pub const WORDS: usize = 8;
    pub const START_BYTE: usize = 0;
    pub const END_BYTE: usize = 1;
    pub const START_UTF16: usize = 2;
    pub const END_UTF16: usize = 3;
    pub const LABEL_START_BYTE: usize = 4;
    pub const LABEL_END_BYTE: usize = 5;
    pub const DEST_START_BYTE: usize = 6;
    pub const DEST_END_BYTE: usize = 7;
}
pub mod block_kind {
    pub const DOCUMENT: u32 = 0;
    pub const PARAGRAPH: u32 = 1;
    pub const HEADING: u32 = 2;
    pub const CODE_BLOCK: u32 = 3;
    pub const HTML_BLOCK: u32 = 4;
    pub const BLOCK_QUOTE: u32 = 5;
    pub const LIST: u32 = 6;
    pub const ITEM: u32 = 7;
    pub const THEMATIC_BREAK: u32 = 8;
    pub const TABLE: u32 = 9;
    pub const TABLE_ROW: u32 = 10;
    pub const TABLE_CELL: u32 = 11;
    pub const FOOTNOTE_DEFINITION: u32 = 12;
    pub const OTHER: u32 = 14;
}
pub mod run_kind {
    pub const TEXT: u32 = 1;
    pub const EMPH: u32 = 2;
    pub const STRONG: u32 = 3;
    pub const CODE: u32 = 4;
    pub const STRIKE: u32 = 5;
    pub const LINK: u32 = 6;
    pub const IMAGE: u32 = 7;
    pub const AUTOLINK: u32 = 8;
    pub const ESCAPE: u32 = 9;
    pub const REPLACEMENT: u32 = 10;
    pub const HARD_BREAK: u32 = 11;
    pub const SOFT_BREAK: u32 = 12;
    pub const HTML_INLINE: u32 = 13;
    pub const FOOTNOTE_REF: u32 = 14;
    pub const OTHER: u32 = 16;
}
pub mod table_alignment {
    pub const NONE: u32 = 0;
    pub const LEFT: u32 = 1;
    pub const CENTER: u32 = 2;
    pub const RIGHT: u32 = 3;
}
