// Generated by native/flark_parse/tool/gen_schema.py from
// native/flark_parse/schema/render_model_v1.json. Do not edit.

// ignore_for_file: constant_identifier_names

abstract final class RenderModelSchema {
  static const int version = 1;
  static const int magic = 0x354B4C46;
  static const int headerWords = 11;
  static const int lineWords = 2;
  static const int blockWords = 14;
  static const int contentWords = 6;
  static const int runWords = 16;
  static const int definitionWords = 8;
}

abstract final class HeaderField {
  static const int magic = 0;
  static const int version = 1;
  static const int srcBytes = 2;
  static const int srcUtf16 = 3;
  static const int lineCount = 4;
  static const int blockCount = 5;
  static const int contentCount = 6;
  static const int runCount = 7;
  static const int definitionCount = 8;
  static const int stringBytes = 9;
  static const int reserved = 10;
}

abstract final class LineField {
  static const int startByte = 0;
  static const int startUtf16 = 1;
}

abstract final class BlockField {
  static const int kind = 0;
  static const int parent = 1;
  static const int startByte = 2;
  static const int endByte = 3;
  static const int startUtf16 = 4;
  static const int endUtf16 = 5;
  static const int firstLine = 6;
  static const int lineCount = 7;
  static const int contentOffset = 8;
  static const int contentCount = 9;
  static const int attr0 = 10;
  static const int attr1 = 11;
  static const int attr2 = 12;
  static const int flags = 13;
}

abstract final class ContentField {
  static const int line = 0;
  static const int startByte = 1;
  static const int startUtf16 = 2;
  static const int endByte = 3;
  static const int endUtf16 = 4;
  static const int virtualLeadingSpaces = 5;
}

abstract final class RunField {
  static const int kind = 0;
  static const int block = 1;
  static const int parent = 2;
  static const int startByte = 3;
  static const int endByte = 4;
  static const int contentStartByte = 5;
  static const int contentEndByte = 6;
  static const int startUtf16 = 7;
  static const int endUtf16 = 8;
  static const int contentStartUtf16 = 9;
  static const int contentEndUtf16 = 10;
  static const int aux0 = 11;
  static const int aux1 = 12;
  static const int aux2 = 13;
  static const int aux3 = 14;
  static const int flags = 15;
}

abstract final class DefinitionField {
  static const int startByte = 0;
  static const int endByte = 1;
  static const int startUtf16 = 2;
  static const int endUtf16 = 3;
  static const int labelStartByte = 4;
  static const int labelEndByte = 5;
  static const int destStartByte = 6;
  static const int destEndByte = 7;
}

abstract final class BlockKind {
  static const int document = 0;
  static const int paragraph = 1;
  static const int heading = 2;
  static const int codeBlock = 3;
  static const int htmlBlock = 4;
  static const int blockQuote = 5;
  static const int list = 6;
  static const int item = 7;
  static const int thematicBreak = 8;
  static const int table = 9;
  static const int tableRow = 10;
  static const int tableCell = 11;
  static const int footnoteDefinition = 12;
  static const int other = 14;
}

abstract final class RunKind {
  static const int text = 1;
  static const int emph = 2;
  static const int strong = 3;
  static const int code = 4;
  static const int strike = 5;
  static const int link = 6;
  static const int image = 7;
  static const int autolink = 8;
  static const int escape = 9;
  static const int replacement = 10;
  static const int hardBreak = 11;
  static const int softBreak = 12;
  static const int htmlInline = 13;
  static const int footnoteRef = 14;
  static const int other = 16;
}

abstract final class TableAlignment {
  static const int none = 0;
  static const int left = 1;
  static const int center = 2;
  static const int right = 3;
}
