// Generated by native/flark_parse/tool/gen_schema.py from
// native/flark_parse/schema/render_model_v5.json. Do not edit.

// ignore_for_file: constant_identifier_names

abstract final class RenderModelSchema {
  static const int version = 5;
  static const int magic = 0x354B4C46;
  static const int headerWords = 12;
  static const int lineWords = 1;
  static const int blockWords = 10;
  static const int contentWords = 4;
  static const int runWords = 4;
  static const int definitionWords = 6;
  static const int runExtraWords = 2;

  /// A block without an extra record.
  static const int noExtra = 0xFFFFFFFF;
}

abstract final class HeaderField {
  static const int magic = 0;
  static const int version = 1;
  static const int srcBytes = 2;
  static const int srcUtf16 = 3;
  static const int lineCount = 4;
  static const int blockCount = 5;
  static const int contentCount = 6;
  static const int runCount = 7;
  static const int definitionCount = 8;
  static const int runExtraCount = 9;
  static const int extraWords = 10;
  static const int stringBytes = 11;
}

abstract final class LineField {
  static const int start = 0;
}

abstract final class BlockField {
  static const int kindFlags = 0;
  static const int parent = 1;
  static const int start = 2;
  static const int end = 3;
  static const int firstLine = 4;
  static const int lineCount = 5;
  static const int contentOffset = 6;
  static const int firstRun = 7;
  static const int attr = 8;
  static const int extra = 9;
}

abstract final class ContentField {
  static const int start = 0;
  static const int end = 1;
  static const int prefixStart = 2;
  static const int lineVirtual = 3;
}

abstract final class RunField {
  static const int start = 0;
  static const int end = 1;
  static const int hidden = 2;
  static const int kindFlagsParent = 3;
}

abstract final class DefinitionField {
  static const int start = 0;
  static const int end = 1;
  static const int labelStart = 2;
  static const int labelEnd = 3;
  static const int destStart = 4;
  static const int destEnd = 5;
}

abstract final class RunExtraField {
  static const int run = 0;
  static const int offset = 1;
}

/// Fields packed into `block.kind_flags`.
abstract final class BlockKindFlags {
  static const int kindShift = 0;
  static const int kindMask = 0xFF;
  static const int flagsShift = 8;
  static const int flagsMask = 0xFFFFFF;
}

/// Fields packed into `content.line_virtual`.
abstract final class ContentLineVirtual {
  static const int lineShift = 0;
  static const int lineMask = 0x3FFFFFFF;
  static const int virtualLeadingSpacesShift = 30;
  static const int virtualLeadingSpacesMask = 0x3;
}

/// Fields packed into `run.hidden`.
abstract final class RunHidden {
  static const int beforeShift = 0;
  static const int beforeMask = 0xFFFF;
  static const int afterShift = 16;
  static const int afterMask = 0xFFFF;
}

/// Fields packed into `run.kind_flags_parent`.
abstract final class RunKindFlagsParent {
  static const int kindShift = 0;
  static const int kindMask = 0xFF;
  static const int flagsShift = 8;
  static const int flagsMask = 0xFF;
  static const int parentDistanceShift = 16;
  static const int parentDistanceMask = 0xFFFF;
}

/// Extra record of fenced `code_block` blocks.
abstract final class CodeBlockExtra {
  static const int words = 2;
  static const int infoStart = 0;
  static const int infoEnd = 1;
}

/// Extra record of `item` blocks.
abstract final class ItemExtra {
  static const int words = 3;
  static const int markerEnd = 0;
  static const int taskStart = 1;
  static const int taskEnd = 2;
}

/// Extra record of `table` blocks.
abstract final class TableExtra {
  static const int words = 1;
  static const int alignments = 0;
}

/// Extra record of `footnote_definition` blocks.
abstract final class FootnoteDefinitionExtra {
  static const int words = 2;
  static const int labelStart = 0;
  static const int labelEnd = 1;
}

/// Extra record of runs with flags bit3; the other kind's record follows.
abstract final class WideRunExtra {
  static const int words = 3;
  static const int contentStart = 0;
  static const int contentEnd = 1;
  static const int parent = 2;
}

/// Extra record of `link`, `image` and `autolink` runs.
abstract final class LinkExtra {
  static const int words = 8;
  static const int destinationStart = 0;
  static const int destinationEnd = 1;
  static const int titleStart = 2;
  static const int titleEnd = 3;
  static const int destinationOffset = 4;
  static const int destinationLength = 5;
  static const int titleOffset = 6;
  static const int titleLength = 7;
}

/// Extra record of `replacement` runs, and `code` runs with flags bit1.
abstract final class DisplayTextExtra {
  static const int words = 2;
  static const int offset = 0;
  static const int length = 1;
}

/// Extra record of `footnote_ref` runs.
abstract final class FootnoteRefExtra {
  static const int words = 2;
  static const int labelStart = 0;
  static const int labelEnd = 1;
}

abstract final class BlockKind {
  static const int document = 0;
  static const int paragraph = 1;
  static const int heading = 2;
  static const int codeBlock = 3;
  static const int htmlBlock = 4;
  static const int blockQuote = 5;
  static const int list = 6;
  static const int item = 7;
  static const int thematicBreak = 8;
  static const int table = 9;
  static const int tableRow = 10;
  static const int tableCell = 11;
  static const int footnoteDefinition = 12;
  static const int other = 14;
}

abstract final class RunKind {
  static const int text = 1;
  static const int emph = 2;
  static const int strong = 3;
  static const int code = 4;
  static const int strike = 5;
  static const int link = 6;
  static const int image = 7;
  static const int autolink = 8;
  static const int escape = 9;
  static const int replacement = 10;
  static const int hardBreak = 11;
  static const int softBreak = 12;
  static const int htmlInline = 13;
  static const int footnoteRef = 14;
  static const int other = 16;
}

abstract final class TableAlignment {
  static const int none = 0;
  static const int left = 1;
  static const int center = 2;
  static const int right = 3;
}
